import type { ConjugationCard } from "../../types";

export const b2Conjugations = [
  {
    id: "cj-b2-1",
    level: "B2",
    verb: "hablar",
    verbMeaning: "говорить",
    tense: "subj-imperfecto",
    tenseLabel: "Subjuntivo imperfecto",
    forms: [
      "hablara",
      "hablaras",
      "hablara",
      "habláramos",
      "hablarais",
      "hablaran",
    ],
    example: {
      es: "Si hablaras español mejor, conseguirías ese trabajo.",
      ru: "Если бы ты говорил по-испански лучше, ты бы получил эту работу.",
    },
    revision: 1,
  },
  {
    id: "cj-b2-2",
    level: "B2",
    verb: "tener",
    verbMeaning: "иметь",
    tense: "pluscuamperfecto",
    tenseLabel: "Pluscuamperfecto de indicativo",
    forms: [
      "había tenido",
      "habías tenido",
      "había tenido",
      "habíamos tenido",
      "habíais tenido",
      "habían tenido",
    ],
    example: {
      es: "Cuando llegamos, ya habían tenido la reunión.",
      ru: "Когда мы приехали, у них уже была встреча.",
    },
    revision: 1,
  },
  {
    id: "cj-b2-3",
    level: "B2",
    verb: "ir",
    verbMeaning: "идти, ехать",
    tense: "subj-imperfecto",
    tenseLabel: "Subjuntivo imperfecto",
    forms: ["fuera", "fueras", "fuera", "fuéramos", "fuerais", "fueran"],
    example: {
      es: "Quería que fuéramos juntos a la fiesta.",
      ru: "Я хотел, чтобы мы пошли на вечеринку вместе.",
    },
    revision: 1,
  },
  {
    id: "cj-b2-4",
    level: "B2",
    verb: "comer",
    verbMeaning: "есть, кушать",
    tense: "futuro-compuesto",
    tenseLabel: "Futuro compuesto",
    forms: [
      "habré comido",
      "habrás comido",
      "habrá comido",
      "habremos comido",
      "habréis comido",
      "habrán comido",
    ],
    example: {
      es: "Para las ocho, ya habremos comido.",
      ru: "К восьми мы уже поедим.",
    },
    revision: 1,
  },
  {
    id: "cj-b2-5",
    level: "B2",
    verb: "ser",
    verbMeaning: "быть",
    tense: "pluscuamperfecto",
    tenseLabel: "Pluscuamperfecto de indicativo",
    forms: [
      "había sido",
      "habías sido",
      "había sido",
      "habíamos sido",
      "habíais sido",
      "habían sido",
    ],
    example: {
      es: "Antes de mudarse, había sido profesor durante diez años.",
      ru: "До переезда он был учителем десять лет.",
    },
    revision: 1,
  },
  {
    id: "cj-b2-6",
    level: "B2",
    verb: "poder",
    verbMeaning: "мочь",
    tense: "subj-imperfecto",
    tenseLabel: "Subjuntivo imperfecto",
    forms: [
      "pudiera",
      "pudieras",
      "pudiera",
      "pudiéramos",
      "pudierais",
      "pudieran",
    ],
    example: {
      es: "Ojalá pudiera viajar más a menudo.",
      ru: "Хоть бы я мог путешествовать чаще.",
    },
    revision: 1,
  },
] satisfies ConjugationCard[];
