import type { GrammarExercise } from "../../types";

export const b2Grammar = [
  {
    id: "b2-01",
    level: "B2",
    topic: "subjuntivo imperfecto",
    type: "fill",
    prompt: "Si (yo/tener) ___ más tiempo, aprendería piano.",
    answer: "tuviera",
    explain:
      'Условное 2 типа (нереальное в настоящем): "si + imperfecto de subjuntivo, condicional". Tener → tuviera/tuviese.',
    revision: 1,
  },
  {
    id: "b2-02",
    level: "B2",
    topic: "condicional tipo 2",
    type: "mcq",
    prompt: "Si yo ___ tú, aceptaría la oferta.",
    options: ["fuera", "soy", "sería", "fui"],
    answer: "fuera",
    explain:
      'Гипотетическое условие: "si + imperfecto subjuntivo (fuera/fuese), + condicional (aceptaría)".',
    revision: 1,
  },
  {
    id: "b2-03",
    level: "B2",
    topic: "condicional tipo 3",
    type: "mcq",
    prompt: "Si me lo ___ dicho, te habría ayudado.",
    options: ["hubieras", "habrías", "has", "hubiste"],
    answer: "hubieras",
    explain:
      'Нереальное условие в прошлом: "si + pluscuamperfecto de subjuntivo (hubieras dicho), + condicional compuesto (habría ayudado)".',
    revision: 1,
  },
  {
    id: "b2-04",
    level: "B2",
    topic: "voz pasiva",
    type: "fill",
    prompt: "La novela (escribir, pasiva) ___ ___ por Cervantes.",
    answer: "fue escrita",
    solvedExample: "La novela fue escrita por Cervantes.",
    explain:
      'Пассивный залог: "ser (в нужном времени) + participio", согласованный в роде/числе с подлежащим: fue escrita.',
    revision: 1,
  },
  {
    id: "b2-05",
    level: "B2",
    topic: "gerundio causal",
    type: "mcq",
    prompt: "___ mucho, aprobó el examen fácilmente.",
    options: ["Estudiando", "Estudia", "Estudiado", "Estudiar"],
    answer: "estudiando",
    explain:
      'Деепричастие (gerundio) может выражать причину или способ: "Estudiando mucho" = "поскольку/благодаря тому, что много учился".',
    revision: 2,
  },
  {
    id: "b2-06",
    level: "B2",
    topic: "verbos de cambio",
    type: "mcq",
    prompt: "Después del accidente, se ___ muy nervioso cada vez que conduce.",
    options: ["pone", "hace", "vuelve", "llega a ser"],
    answer: "pone",
    explain:
      '"Ponerse + adjetivo" выражает временное эмоциональное/физическое изменение: se pone nervioso. "Volverse" — более устойчивое изменение характера.',
    revision: 1,
  },
  {
    id: "b2-07",
    level: "B2",
    topic: "subjuntivo — duda/emoción",
    type: "fill",
    prompt: "Me sorprendió que no me (tú/llamar) ___ ayer.",
    answer: "llamaras",
    explain:
      'После выражения эмоции в прошедшем времени ("me sorprendió que") используется imperfecto de subjuntivo: llamaras.',
    revision: 2,
  },
  {
    id: "b2-08",
    level: "B2",
    topic: "concesivas",
    type: "mcq",
    prompt: "Aunque ___ mucho dinero, no sería feliz sin amigos.",
    options: ["tuviera", "tengo", "tuve", "tendría"],
    answer: "tuviera",
    explain:
      '"Aunque" с гипотетическим, нереальным смыслом требует subjuntivo (tuviera); с фактом — indicativo (tengo).',
    revision: 1,
  },
  {
    id: "b2-09",
    level: "B2",
    topic: "pluscuamperfecto",
    type: "fill",
    prompt: "Cuando llegamos, la película ya (empezar) ___ ___.",
    answer: "había empezado",
    solvedExample: "Cuando llegamos, la película ya había empezado.",
    explain:
      "Pluscuamperfecto (había + participio) описывает действие, завершившееся до другого прошедшего действия: había empezado.",
    revision: 1,
  },
  {
    id: "b2-10",
    level: "B2",
    topic: "futuro compuesto",
    type: "mcq",
    prompt: "Para el año 2030, los científicos ___ una cura.",
    options: [
      "habrán encontrado",
      "encontrarán",
      "han encontrado",
      "encuentran",
    ],
    answer: "habrán encontrado",
    explain:
      "Futuro compuesto (habrá + participio) выражает действие, которое будет завершено к определённому моменту в будущем.",
    revision: 1,
  },
  {
    id: "b2-11",
    level: "B2",
    topic: "lo que",
    type: "mcq",
    prompt: "No entiendo ___ quieres decir.",
    options: ["lo que", "que", "lo cual", "cual"],
    answer: "lo que",
    explain:
      '"Lo que" используется для обозначения абстрактной идеи или неопределённого предмета ("то, что"): no entiendo lo que quieres decir.',
    revision: 1,
  },
  {
    id: "b2-12",
    level: "B2",
    topic: "verbos con preposición",
    type: "mcq",
    prompt: "Por fin me acostumbré ___ vivir aquí.",
    options: ["a", "de", "en", "con"],
    answer: "a",
    explain:
      '"Acostumbrarse a" — устойчивое сочетание глагола с предлогом "a".',
    revision: 1,
  },
  {
    id: "b2-13",
    level: "B2",
    topic: "discurso indirecto",
    type: "mcq",
    prompt: "Me preguntó si ___ ir con ellos al cine.",
    options: ["quería", "quiero", "querré", "quise"],
    answer: "quería",
    explain:
      "В косвенном вопросе после глагола в прошедшем времени presente переходит в imperfecto: quiero → quería.",
    revision: 1,
  },
  {
    id: "b2-14",
    level: "B2",
    topic: "cuál vs qué",
    type: "mcq",
    prompt: "¿___ es tu color favorito?",
    options: ["Cuál", "Qué", "Cual es", "Que"],
    answer: "cuál",
    explain:
      '"Cuál" используется перед глаголом "ser" для выбора из группы вариантов: ¿Cuál es tu color favorito?',
    revision: 1,
  },
  {
    id: "b2-15",
    level: "B2",
    topic: "condicional tipo 3",
    type: "fill",
    prompt: "Si (yo/saber) ___ la verdad, te la habría dicho.",
    answer: "hubiera sabido",
    explain:
      'Нереальное условие в прошлом: "si + pluscuamperfecto de subjuntivo, + condicional compuesto". Saber → hubiera sabido.',
    revision: 1,
  },
  {
    id: "b2-16",
    level: "B2",
    topic: "voz pasiva",
    type: "fill",
    prompt: "El puente (construir, pasiva) ___ ___ en 1920.",
    answer: "fue construido",
    solvedExample: "El puente fue construido en 1920.",
    explain:
      "Пассивный залог: ser (в прошедшем времени) + participio, согласованный с подлежащим (el puente — м.р.): fue construido.",
    revision: 1,
  },
  {
    id: "b2-17",
    level: "B2",
    topic: "gerundio",
    type: "fill",
    prompt: "(Caminar) ___ por la calle, vi a mi amigo.",
    answer: "caminando",
    explain:
      "Деепричастие (gerundio) в начале фразы выражает одновременное действие: caminando por la calle, vi...",
    revision: 1,
  },
  {
    id: "b2-18",
    level: "B2",
    topic: "pluscuamperfecto",
    type: "fill",
    prompt: "Cuando llegué, ellos ya (salir) ___ ___.",
    answer: "habían salido",
    solvedExample: "Cuando llegué, ellos ya habían salido.",
    explain:
      "Pluscuamperfecto (había + participio) описывает действие, завершившееся раньше другого прошедшего действия.",
    revision: 1,
  },
  {
    id: "b2-19",
    level: "B2",
    topic: "futuro compuesto",
    type: "fill",
    prompt: "Para diciembre, (nosotros/terminar) ___ ___ el curso.",
    answer: "habremos terminado",
    solvedExample: "Para diciembre, habremos terminado el curso.",
    explain:
      "Futuro compuesto (habremos + participio) выражает действие, которое будет завершено к определённому моменту будущего.",
    revision: 1,
  },
  {
    id: "b2-20",
    level: "B2",
    topic: "verbos con preposición",
    type: "fill",
    prompt: "Los niños se rieron ___ el payaso.",
    answer: "de",
    explain:
      '"Reírse de algo/alguien" — устойчивое сочетание "смеяться над кем-то/чем-то".',
    revision: 1,
  },
] satisfies GrammarExercise[];
