import type { VocabularyCard } from "../../types";

export const b2Vocabulary = [
  {
    id: "v-b2-1",
    level: "B2",
    word: "exigir",
    translation: "требовать",
    accept: ["требовать"],
    context: "Los empleados exigen mejores condiciones.",
    revision: 1,
  },
  {
    id: "v-b2-2",
    level: "B2",
    word: "fomentar",
    translation: "способствовать",
    accept: ["способствовать", "поощрять"],
    context: "El gobierno quiere fomentar el turismo rural.",
    revision: 1,
  },
  {
    id: "v-b2-3",
    level: "B2",
    word: "desempeñar",
    translation: "выполнять",
    accept: ["выполнять", "исполнять"],
    context: "Desempeña un papel clave en la empresa.",
    revision: 1,
  },
  {
    id: "v-b2-4",
    level: "B2",
    word: "abarcar",
    translation: "охватывать",
    accept: ["охватывать"],
    context: "El proyecto abarca varios países.",
    revision: 1,
  },
  {
    id: "v-b2-5",
    level: "B2",
    word: "plantear",
    translation: "ставить вопрос",
    accept: ["ставить вопрос", "предлагать", "поднимать вопрос"],
    context: "El informe plantea varias preguntas importantes.",
    revision: 1,
  },
  {
    id: "v-b2-6",
    level: "B2",
    word: "destacar",
    translation: "выделяться",
    accept: ["выделяться", "подчёркивать"],
    context: "Quiero destacar la importancia de este tema.",
    revision: 1,
  },
  {
    id: "v-b2-7",
    level: "B2",
    word: "carecer",
    translation: "не иметь",
    accept: ["не иметь", "испытывать нехватку"],
    context: "La región carece de recursos básicos.",
    revision: 1,
  },
  {
    id: "v-b2-8",
    level: "B2",
    word: "suscitar",
    translation: "вызывать",
    accept: ["вызывать"],
    context: "La noticia suscitó mucha polémica.",
    revision: 1,
  },
  {
    id: "v-b2-9",
    level: "B2",
    word: "ámbito",
    translation: "сфера",
    accept: ["сфера", "область"],
    context: "Trabaja en el ámbito de la educación.",
    revision: 1,
  },
  {
    id: "v-b2-10",
    level: "B2",
    word: "rentable",
    translation: "рентабельный",
    accept: ["рентабельный", "выгодный"],
    context: "El nuevo modelo de negocio es muy rentable.",
    revision: 1,
  },
  {
    id: "v-b2-11",
    level: "B2",
    word: "imprescindible",
    translation: "незаменимый",
    accept: ["незаменимый", "необходимый"],
    context: "El agua es imprescindible para la vida.",
    revision: 1,
  },
  {
    id: "v-b2-12",
    level: "B2",
    word: "matizar",
    translation: "уточнять",
    accept: ["уточнять"],
    context: "Quiero matizar lo que dije antes.",
    revision: 1,
  },
  {
    id: "v-b2-13",
    level: "B2",
    word: "constatar",
    translation: "констатировать",
    accept: ["констатировать", "убедиться"],
    context: "Los investigadores constataron un aumento significativo.",
    revision: 1,
  },
  {
    id: "v-b2-14",
    level: "B2",
    word: "índole",
    translation: "характер",
    accept: ["характер", "природа"],
    context: "Es un problema de índole económica.",
    revision: 1,
  },
] satisfies VocabularyCard[];
