import type { ConjugationCard } from "../../types";

export const b1Conjugations = [
  {
    id: "cj-b1-1",
    level: "B1",
    verb: "hablar",
    verbMeaning: "говорить",
    tense: "subj-presente",
    tenseLabel: "Subjuntivo presente",
    forms: ["hable", "hables", "hable", "hablemos", "habléis", "hablen"],
    example: {
      es: "Espero que hables con ella pronto.",
      ru: "Надеюсь, ты скоро поговоришь с ней.",
    },
    revision: 1,
  },
  {
    id: "cj-b1-2",
    level: "B1",
    verb: "tener",
    verbMeaning: "иметь",
    tense: "condicional",
    tenseLabel: "Condicional simple",
    forms: [
      "tendría",
      "tendrías",
      "tendría",
      "tendríamos",
      "tendríais",
      "tendrían",
    ],
    example: {
      es: "Yo tendría más tiempo si no trabajara tanto.",
      ru: "У меня было бы больше времени, если бы я не работал так много.",
    },
    revision: 1,
  },
  {
    id: "cj-b1-3",
    level: "B1",
    verb: "comer",
    verbMeaning: "есть, кушать",
    tense: "pret-perfecto",
    tenseLabel: "Pretérito perfecto compuesto",
    forms: [
      "he comido",
      "has comido",
      "ha comido",
      "hemos comido",
      "habéis comido",
      "han comido",
    ],
    example: {
      es: "Hoy no he comido nada todavía.",
      ru: "Сегодня я ещё ничего не ел.",
    },
    revision: 1,
  },
  {
    id: "cj-b1-4",
    level: "B1",
    verb: "ser",
    verbMeaning: "быть",
    tense: "subj-presente",
    tenseLabel: "Subjuntivo presente",
    forms: ["sea", "seas", "sea", "seamos", "seáis", "sean"],
    example: {
      es: "Ojalá el examen sea fácil.",
      ru: "Хоть бы экзамен оказался лёгким.",
    },
    revision: 1,
  },
  {
    id: "cj-b1-5",
    level: "B1",
    verb: "poder",
    verbMeaning: "мочь",
    tense: "condicional",
    tenseLabel: "Condicional simple",
    forms: ["podría", "podrías", "podría", "podríamos", "podríais", "podrían"],
    example: {
      es: "¿Podrías ayudarme con esto?",
      ru: "Не мог бы ты помочь мне с этим?",
    },
    revision: 1,
  },
  {
    id: "cj-b1-6",
    level: "B1",
    verb: "vivir",
    verbMeaning: "жить",
    tense: "pret-perfecto",
    tenseLabel: "Pretérito perfecto compuesto",
    forms: [
      "he vivido",
      "has vivido",
      "ha vivido",
      "hemos vivido",
      "habéis vivido",
      "han vivido",
    ],
    example: {
      es: "¿Alguna vez has vivido en el extranjero?",
      ru: "Ты когда-нибудь жил за границей?",
    },
    revision: 1,
  },
] satisfies ConjugationCard[];
