import type { GrammarExercise } from "../../types";

export const b1Grammar = [
  {
    id: "b1-01",
    level: "B1",
    topic: "subjuntivo — formación",
    type: "fill",
    prompt: "Quiero que tú (hablar) ___ con ella.",
    answer: "hables",
    explain:
      'После "querer que" используется subjuntivo. Для -ar глаголов: habl<b>e</b>, habl<b>es</b>, hable, hablemos, habléis, hablen.',
    revision: 1,
  },
  {
    id: "b1-02",
    level: "B1",
    topic: "subjuntivo — deseo",
    type: "mcq",
    prompt: "Espero que (vosotros) ___ un buen viaje.",
    options: ["tengáis", "tenéis", "tendréis", "tuvierais"],
    answer: "tengáis",
    explain:
      '"Esperar que" вводит subjuntivo. Tener → teng- (неправильная основа) + окончания subjuntivo: tengáis.',
    revision: 1,
  },
  {
    id: "b1-03",
    level: "B1",
    topic: "subjuntivo vs indicativo",
    type: "mcq",
    prompt: "Creo que ella ___ razón. / No creo que ella ___ razón.",
    options: [
      "tiene / tenga",
      "tenga / tiene",
      "tiene / tiene",
      "tenga / tenga",
    ],
    answer: "tiene / tenga",
    solvedExample: "Creo que ella tiene razón. / No creo que ella tenga razón.",
    explain:
      '"Creer que" (утверждение) требует indicativo: tiene. "No creer que" (отрицание/сомнение) требует subjuntivo: tenga.',
    revision: 1,
  },
  {
    id: "b1-04",
    level: "B1",
    topic: "condicional simple",
    type: "fill",
    prompt: "En tu lugar, yo (hablar) ___ con el jefe.",
    answer: "hablaría",
    explain:
      "Кондиционал = инфинитив + окончания имперфекта: hablar<b>ía</b>. Используется для советов и гипотез: yo hablaría.",
    revision: 1,
  },
  {
    id: "b1-05",
    level: "B1",
    topic: "futuro de probabilidad",
    type: "mcq",
    prompt: "No sé dónde está Juan. ___ en casa.",
    options: ["Estará", "Está", "Estuvo", "Estaría"],
    answer: "estará",
    explain:
      'Простое будущее время может выражать предположение о настоящем: "estará en casa" = "наверное, он дома".',
    revision: 1,
  },
  {
    id: "b1-06",
    level: "B1",
    topic: "pretérito perfecto",
    type: "fill",
    prompt: "Esta mañana (yo/desayunar) ___ ___ muy poco.",
    answer: "he desayunado",
    solvedExample: "Esta mañana he desayunado muy poco.",
    explain:
      "Pretérito perfecto compuesto (haber + participio) используется для действий в недавнем/незавершённом временном отрезке: he desayunado.",
    revision: 1,
  },
  {
    id: "b1-07",
    level: "B1",
    topic: "por / para",
    type: "mcq",
    prompt: "Este regalo es ___ ti.",
    options: ["para", "por", "a", "de"],
    answer: "para",
    explain:
      '"Para" указывает получателя/цель: para ti (для тебя). "Por" используется для причины, обмена, средства передвижения и т.д.',
    revision: 1,
  },
  {
    id: "b1-08",
    level: "B1",
    topic: "por / para",
    type: "mcq",
    prompt: "Pasamos ___ el parque para llegar antes.",
    options: ["por", "para", "a", "en"],
    answer: "por",
    explain:
      '"Por" указывает движение через место: pasar por el parque (проходить через парк).',
    revision: 1,
  },
  {
    id: "b1-09",
    level: "B1",
    topic: "pronombres relativos",
    type: "mcq",
    prompt: "El hombre ___ vive al lado es médico.",
    options: ["que", "quien", "cual", "donde"],
    answer: "que",
    explain:
      '"Que" — самое универсальное относительное местоимение для людей и предметов в ограничительных придаточных: el hombre que vive...',
    revision: 1,
  },
  {
    id: "b1-10",
    level: "B1",
    topic: "pasiva refleja",
    type: "mcq",
    prompt: "___ habla español en muchos países.",
    options: ["Se", "Es", "Está", "Hay"],
    answer: "se",
    explain:
      'Безличная пассивная конструкция "se + глагол в 3-м лице" описывает действие без указания субъекта: se habla español.',
    revision: 1,
  },
  {
    id: "b1-11",
    level: "B1",
    topic: "imperativo afirmativo",
    type: "fill",
    prompt: "(tú/cerrar) ___ la puerta, por favor.",
    answer: "cierra",
    explain:
      'Утвердительный императив для "tú" у глаголов с изменением корня (e→ie): cierra (от cerrar).',
    revision: 1,
  },
  {
    id: "b1-12",
    level: "B1",
    topic: "imperativo negativo",
    type: "mcq",
    prompt: "No ___ tarde a la reunión.",
    options: ["llegues", "llegas", "llega", "llegar"],
    answer: "llegues",
    explain:
      'Отрицательный императив всегда образуется от subjuntivo: no llegues (а не llega). Для "tú" у глаголов на -ar окончание -es.',
    revision: 1,
  },
  {
    id: "b1-13",
    level: "B1",
    topic: "pronombres dobles",
    type: "mcq",
    prompt: "¿El libro? ___ di a María ayer.",
    options: ["Se lo", "Le lo", "Lo le", "Se la"],
    answer: "se lo",
    explain:
      'Когда косвенное "le/les" стоит перед прямым "lo/la/los/las", "le/les" меняется на <b>se</b>: se lo di (= le di el libro).',
    revision: 1,
  },
  {
    id: "b1-14",
    level: "B1",
    topic: "estilo indirecto",
    type: "mcq",
    prompt: 'Ella dijo: "Estoy cansada." → Ella dijo que ___ cansada.',
    options: ["estaba", "está", "estuvo", "esté"],
    answer: "estaba",
    explain:
      'В косвенной речи после глагола в прошедшем времени ("dijo") presente переходит в imperfecto: estoy → estaba.',
    revision: 1,
  },
  {
    id: "b1-15",
    level: "B1",
    topic: "subjuntivo — ojalá",
    type: "fill",
    prompt: "Ojalá (nosotros/aprobar) ___ el examen.",
    answer: "aprobemos",
    explain:
      '"Ojalá" всегда требует subjuntivo, независимо от контекста: ojalá aprobemos.',
    revision: 1,
  },
  {
    id: "b1-16",
    level: "B1",
    topic: "condicional — cortesía",
    type: "fill",
    prompt: "¿(Tú) ___ (poder) ayudarme mañana?",
    answer: "podrías",
    explain:
      "Condicional часто используется для вежливых просьб. Poder — неправильная основа podr- + окончания имперфекта: podrías.",
    revision: 1,
  },
  {
    id: "b1-17",
    level: "B1",
    topic: "pretérito perfecto",
    type: "fill",
    prompt: "¿Alguna vez (tú/estar) ___ en Argentina?",
    answer: "has estado",
    explain:
      "Pretérito perfecto (haber + participio) используется для вопросов об опыте в жизни: ¿has estado alguna vez...?",
    revision: 1,
  },
  {
    id: "b1-18",
    level: "B1",
    topic: "imperativo formal",
    type: "fill",
    prompt: "(Usted/hablar) ___ más despacio, por favor.",
    answer: "hable",
    explain:
      "Формальный императив (usted) образуется от формы subjuntivo: hable (не *habla).",
    revision: 1,
  },
  {
    id: "b1-19",
    level: "B1",
    topic: "por / para",
    type: "fill",
    prompt: "Trabajo ___ ganar dinero.",
    answer: "para",
    explain:
      '"Para + infinitivo" выражает цель действия: trabajo para ganar dinero (работаю, чтобы зарабатывать).',
    revision: 1,
  },
  {
    id: "b1-20",
    level: "B1",
    topic: "pronombres relativos",
    type: "fill",
    prompt: "La ciudad ___ nací es muy pequeña.",
    answer: "donde",
    explain:
      '"Donde" используется как относительное местоимение для мест: la ciudad donde nací.',
    revision: 1,
  },
] satisfies GrammarExercise[];
