import type { VocabularyCard } from "../../types";

const b1VocabularyBase = [
  {
    id: "v-b1-1",
    level: "B1",
    word: "logro",
    translation: "достижение",
    accept: ["достижение"],
    context: "Graduarse fue un gran logro para ella.",
    contextTarget: "logro",
    revision: 1,
  },
  {
    id: "v-b1-2",
    level: "B1",
    word: "desafío",
    translation: "вызов",
    accept: ["вызов", "трудность"],
    context: "Aprender un idioma nuevo es un desafío.",
    contextTarget: "desafío",
    revision: 1,
  },
  {
    id: "v-b1-3",
    level: "B1",
    word: "ventaja",
    translation: "преимущество",
    accept: ["преимущество", "плюс"],
    context: "Trabajar desde casa tiene muchas ventajas.",
    contextTarget: "ventajas",
    revision: 1,
  },
  {
    id: "v-b1-4",
    level: "B1",
    word: "desventaja",
    translation: "недостаток",
    accept: ["недостаток", "минус"],
    context: "Esa decisión también tiene desventajas.",
    contextTarget: "desventajas",
    revision: 1,
  },
  {
    id: "v-b1-5",
    level: "B1",
    word: "objetivo",
    translation: "цель",
    accept: ["цель"],
    context: "Mi objetivo es aprender español en un año.",
    contextTarget: "objetivo",
    revision: 1,
  },
  {
    id: "v-b1-6",
    level: "B1",
    word: "herramienta",
    translation: "инструмент",
    accept: ["инструмент"],
    context: "Internet es una herramienta muy útil.",
    contextTarget: "herramienta",
    revision: 1,
  },
  {
    id: "v-b1-7",
    level: "B1",
    word: "esfuerzo",
    translation: "усилие",
    accept: ["усилие", "старание"],
    context: "Consiguió el trabajo con mucho esfuerzo.",
    contextTarget: "esfuerzo",
    revision: 1,
  },
  {
    id: "v-b1-8",
    level: "B1",
    word: "investigación",
    translation: "исследование",
    accept: ["исследование"],
    context: "Publicaron una nueva investigación sobre el clima.",
    contextTarget: "investigación",
    revision: 1,
  },
  {
    id: "v-b1-9",
    level: "B1",
    word: "sociedad",
    translation: "общество",
    accept: ["общество"],
    context: "La sociedad está cambiando rápidamente.",
    contextTarget: "sociedad",
    revision: 1,
  },
  {
    id: "v-b1-10",
    level: "B1",
    word: "rasgo",
    translation: "черта",
    accept: ["черта", "особенность"],
    context: "La honestidad es su mejor rasgo.",
    contextTarget: "rasgo",
    revision: 1,
  },
  {
    id: "v-b1-11",
    level: "B1",
    word: "acuerdo",
    translation: "соглашение",
    accept: ["соглашение", "договорённость"],
    context: "Llegaron a un acuerdo después de horas de debate.",
    contextTarget: "acuerdo",
    revision: 1,
  },
  {
    id: "v-b1-12",
    level: "B1",
    word: "suceso",
    translation: "событие",
    accept: ["событие", "происшествие"],
    context: "Fue un suceso inesperado.",
    contextTarget: "suceso",
    revision: 1,
  },
  {
    id: "v-b1-13",
    level: "B1",
    word: "propuesta",
    translation: "предложение",
    accept: ["предложение"],
    context: "Presentaron una propuesta interesante.",
    contextTarget: "propuesta",
    revision: 1,
  },
  {
    id: "v-b1-14",
    level: "B1",
    word: "medio ambiente",
    translation: "окружающая среда",
    accept: ["окружающая среда", "экология"],
    context: "Debemos cuidar el medio ambiente.",
    contextTarget: "medio ambiente",
    revision: 1,
  },
  {
    id: "v-b1-15",
    level: "B1",
    word: "empleo",
    translation: "работа, занятость",
    accept: ["работа", "занятость", "рабочее место"],
    context: "Encontrar un empleo estable no es fácil hoy en día.",
    contextTarget: "empleo",
    revision: 1,
  },
  {
    id: "v-b1-16",
    level: "B1",
    word: "sueldo",
    translation: "зарплата",
    accept: ["зарплата", "оклад", "жалованье"],
    context: "Cobra un buen sueldo, pero trabaja muchas horas.",
    contextTarget: "sueldo",
    revision: 1,
  },
  {
    id: "v-b1-17",
    level: "B1",
    word: "jefe",
    translation: "начальник",
    accept: ["начальник", "шеф", "руководитель"],
    context: "Mi jefe me pidió un informe para el lunes.",
    contextTarget: "jefe",
    revision: 1,
  },
  {
    id: "v-b1-18",
    level: "B1",
    word: "entrevista",
    translation: "собеседование, интервью",
    accept: ["собеседование", "интервью"],
    context: "Estoy nervioso porque mañana tengo una entrevista de trabajo.",
    contextTarget: "entrevista",
    revision: 1,
  },
  {
    id: "v-b1-19",
    level: "B1",
    word: "huelga",
    translation: "забастовка",
    accept: ["забастовка", "стачка"],
    context: "Los trabajadores del metro están en huelga.",
    contextTarget: "huelga",
    revision: 1,
  },
  {
    id: "v-b1-20",
    level: "B1",
    word: "contaminación",
    translation: "загрязнение",
    accept: ["загрязнение", "загрязнённость"],
    context: "La contaminación del aire es un problema grave en las ciudades.",
    contextTarget: "contaminación",
    revision: 1,
  },
  {
    id: "v-b1-21",
    level: "B1",
    word: "reciclaje",
    translation: "переработка (отходов)",
    accept: ["переработка", "рециклинг", "утилизация"],
    context: "El reciclaje del papel y del vidrio ayuda al planeta.",
    contextTarget: "reciclaje",
    revision: 1,
  },
  {
    id: "v-b1-22",
    level: "B1",
    word: "sequía",
    translation: "засуха",
    accept: ["засуха"],
    context: "Este verano ha habido una sequía muy fuerte.",
    contextTarget: "sequía",
    revision: 1,
  },
  {
    id: "v-b1-23",
    level: "B1",
    word: "pantalla",
    translation: "экран",
    accept: ["экран", "дисплей"],
    context: "Pasa demasiadas horas delante de la pantalla.",
    contextTarget: "pantalla",
    revision: 1,
  },
  {
    id: "v-b1-24",
    level: "B1",
    word: "contraseña",
    translation: "пароль",
    accept: ["пароль"],
    context: "Olvidé la contraseña de mi correo electrónico.",
    contextTarget: "contraseña",
    revision: 1,
  },
  {
    id: "v-b1-25",
    level: "B1",
    word: "enfermedad",
    translation: "болезнь",
    accept: ["болезнь", "заболевание"],
    context: "El médico dice que no es una enfermedad grave.",
    contextTarget: "enfermedad",
    revision: 1,
  },
  {
    id: "v-b1-26",
    level: "B1",
    word: "tratamiento",
    translation: "лечение",
    accept: ["лечение", "курс лечения"],
    context: "El tratamiento dura dos semanas.",
    contextTarget: "tratamiento",
    revision: 1,
  },
  {
    id: "v-b1-27",
    level: "B1",
    word: "bienestar",
    translation: "благополучие",
    accept: ["благополучие", "благосостояние", "хорошее самочувствие"],
    context: "El deporte mejora el bienestar físico y mental.",
    contextTarget: "bienestar",
    revision: 1,
  },
  {
    id: "v-b1-28",
    level: "B1",
    word: "ciudadano",
    translation: "гражданин",
    accept: ["гражданин", "житель"],
    context: "Todo ciudadano tiene derechos y deberes.",
    contextTarget: "ciudadano",
    revision: 1,
  },
  {
    id: "v-b1-29",
    level: "B1",
    word: "gobierno",
    translation: "правительство",
    accept: ["правительство", "власть"],
    context: "El gobierno ha anunciado nuevas medidas económicas.",
    contextTarget: "gobierno",
    revision: 1,
  },
  {
    id: "v-b1-30",
    level: "B1",
    word: "ley",
    translation: "закон",
    accept: ["закон"],
    context: "La nueva ley entra en vigor el próximo año.",
    contextTarget: "ley",
    revision: 1,
  },
  {
    id: "v-b1-31",
    level: "B1",
    word: "desarrollo",
    translation: "развитие",
    accept: ["развитие"],
    context: "La tecnología favorece el desarrollo económico del país.",
    contextTarget: "desarrollo",
    revision: 1,
  },
  {
    id: "v-b1-32",
    level: "B1",
    word: "encuesta",
    translation: "опрос",
    accept: ["опрос", "анкетирование"],
    context: "Según una encuesta reciente, la mayoría está a favor.",
    contextTarget: "encuesta",
    revision: 1,
  },
  {
    id: "v-b1-33",
    level: "B1",
    word: "lograr",
    translation: "добиваться, достигать",
    accept: ["добиваться", "достигать", "суметь"],
    context: "Con esfuerzo logró aprobar todos los exámenes.",
    contextTarget: "logró",
    revision: 1,
  },
  {
    id: "v-b1-34",
    level: "B1",
    word: "mejorar",
    translation: "улучшать(ся)",
    accept: ["улучшать", "улучшить", "улучшаться"],
    context: "Quiere mejorar su nivel de español este año.",
    contextTarget: "mejorar",
    revision: 1,
  },
  {
    id: "v-b1-35",
    level: "B1",
    word: "desarrollar",
    translation: "развивать",
    accept: ["развивать", "разрабатывать"],
    context: "La empresa quiere desarrollar una nueva aplicación.",
    contextTarget: "desarrollar",
    revision: 1,
  },
  {
    id: "v-b1-36",
    level: "B1",
    word: "quejarse",
    translation: "жаловаться",
    accept: ["жаловаться", "пожаловаться"],
    context: "Los vecinos se quejan del ruido por las noches.",
    contextTarget: "se quejan",
    revision: 1,
  },
  {
    id: "v-b1-37",
    level: "B1",
    word: "aumentar",
    translation: "увеличивать(ся)",
    accept: ["увеличивать", "увеличиваться", "расти", "повышаться"],
    context: "El precio de la vivienda ha aumentado mucho.",
    contextTarget: "aumentado",
    revision: 1,
  },
  {
    id: "v-b1-38",
    level: "B1",
    word: "disminuir",
    translation: "уменьшать(ся)",
    accept: ["уменьшать", "уменьшаться", "снижаться", "сокращаться"],
    context: "El número de accidentes ha disminuido este año.",
    contextTarget: "disminuido",
    revision: 1,
  },
  {
    id: "v-b1-39",
    level: "B1",
    word: "exigir",
    translation: "требовать",
    accept: ["требовать", "потребовать"],
    context: "Los estudiantes exigen una respuesta clara.",
    contextTarget: "exigen",
    revision: 1,
  },
  {
    id: "v-b1-40",
    level: "B1",
    word: "compartir",
    translation: "делиться, разделять",
    accept: ["делиться", "разделять", "поделиться"],
    context: "Me gusta compartir mis ideas con el grupo.",
    contextTarget: "compartir",
    revision: 1,
  },
  {
    id: "v-b1-41",
    level: "B1",
    word: "apoyar",
    translation: "поддерживать",
    accept: ["поддерживать", "поддержать"],
    context: "Mi familia siempre me apoya en mis decisiones.",
    contextTarget: "apoya",
    revision: 1,
  },
  {
    id: "v-b1-42",
    level: "B1",
    word: "atreverse",
    translation: "осмеливаться, решаться",
    accept: ["осмеливаться", "решаться", "отваживаться"],
    context: "No se atreve a hablar en público.",
    contextTarget: "se atreve",
    revision: 1,
  },
  {
    id: "v-b1-43",
    level: "B1",
    word: "imprescindible",
    translation: "необходимый, незаменимый",
    accept: ["необходимый", "незаменимый", "обязательный"],
    context: "Para este puesto es imprescindible saber inglés.",
    contextTarget: "imprescindible",
    revision: 1,
  },
  {
    id: "v-b1-44",
    level: "B1",
    word: "asequible",
    translation: "доступный (по цене)",
    accept: ["доступный", "по карману", "недорогой"],
    context: "Buscamos un piso a un precio asequible.",
    contextTarget: "asequible",
    revision: 1,
  },
  {
    id: "v-b1-45",
    level: "B1",
    word: "exitoso",
    translation: "успешный",
    accept: ["успешный", "удачный"],
    context: "Fue una campaña muy exitosa.",
    contextTarget: "exitosa",
    revision: 1,
  },
  {
    id: "v-b1-46",
    level: "B1",
    word: "cotidiano",
    translation: "повседневный",
    accept: ["повседневный", "ежедневный", "будничный"],
    context: "El móvil forma parte de la vida cotidiana.",
    contextTarget: "cotidiana",
    revision: 1,
  },
  {
    id: "v-b1-47",
    level: "B1",
    word: "sostenible",
    translation: "устойчивый, экологичный",
    accept: ["устойчивый", "экологичный", "рациональный"],
    context: "Apuestan por un turismo más sostenible.",
    contextTarget: "sostenible",
    revision: 1,
  },
  {
    id: "v-b1-48",
    level: "B1",
    word: "eficaz",
    translation: "эффективный, действенный",
    accept: ["эффективный", "действенный", "результативный"],
    context: "Es un método muy eficaz para memorizar palabras.",
    contextTarget: "eficaz",
    revision: 1,
  },
  {
    id: "v-b1-49",
    level: "B1",
    word: "a pesar de",
    translation: "несмотря на",
    accept: ["несмотря на", "вопреки"],
    context: "A pesar de la lluvia, salimos a pasear.",
    contextTarget: "A pesar de",
    revision: 1,
  },
  {
    id: "v-b1-50",
    level: "B1",
    word: "por lo tanto",
    translation: "следовательно, поэтому",
    accept: ["следовательно", "поэтому", "таким образом"],
    context: "No estudió; por lo tanto, suspendió el examen.",
    contextTarget: "por lo tanto",
    revision: 1,
  },
] satisfies VocabularyCard[];

const b1VocabularyDetails: Record<
  string,
  Pick<
    VocabularyCard,
    | "partOfSpeech"
    | "gender"
    | "forms"
    | "contextTranslation"
    | "collocations"
    | "usageNote"
    | "register"
  >
> = {
  "v-b1-1": {
    partOfSpeech: "существительное",
    gender: "мужской",
    forms: ["el logro", "los logros"],
    contextTranslation:
      "Окончить университет было для неё большим достижением.",
    collocations: ["alcanzar un logro", "un gran logro"],
    usageNote:
      "Logro подчёркивает успешно достигнутый результат; objetivo — ещё только цель.",
    register: "нейтральный",
  },
  "v-b1-2": {
    partOfSpeech: "существительное",
    gender: "мужской",
    forms: ["el desafío", "los desafíos"],
    contextTranslation: "Изучение нового языка — это вызов.",
    collocations: ["afrontar un desafío", "un desafío difícil"],
    usageNote:
      "Desafío может обозначать и трудную задачу, и прямой вызов другому человеку.",
    register: "нейтральный",
  },
  "v-b1-3": {
    partOfSpeech: "существительное",
    gender: "женский",
    forms: ["la ventaja", "las ventajas"],
    contextTranslation: "У работы из дома много преимуществ.",
    collocations: ["tener la ventaja de", "ventajas e inconvenientes"],
    usageNote:
      "Для сопоставления часто используется конструкция la ventaja es que.",
    register: "нейтральный",
  },
  "v-b1-4": {
    partOfSpeech: "существительное",
    gender: "женский",
    forms: ["la desventaja", "las desventajas"],
    contextTranslation: "У этого решения тоже есть недостатки.",
    collocations: ["una clara desventaja", "tener la desventaja de"],
    usageNote:
      "Desventaja — прямой антоним ventaja; в разговорной речи возможны pro и contra.",
    register: "нейтральный",
  },
  "v-b1-5": {
    partOfSpeech: "существительное",
    gender: "мужской",
    forms: ["el objetivo", "los objetivos"],
    contextTranslation: "Моя цель — выучить испанский за год.",
    collocations: ["alcanzar un objetivo", "tener como objetivo"],
    usageNote:
      "После mi objetivo es обычно ставится infinitivo, когда субъект действия тот же.",
    register: "нейтральный",
  },
  "v-b1-6": {
    partOfSpeech: "существительное",
    gender: "женский",
    forms: ["la herramienta", "las herramientas"],
    contextTranslation: "Интернет — очень полезный инструмент.",
    collocations: ["herramienta útil", "herramienta de trabajo"],
    usageNote:
      "Слово употребляется и буквально, и метафорически для метода или технологии.",
    register: "нейтральный",
  },
  "v-b1-7": {
    partOfSpeech: "существительное",
    gender: "мужской",
    forms: ["el esfuerzo", "los esfuerzos"],
    contextTranslation: "Она получила эту работу благодаря большим усилиям.",
    collocations: ["hacer un esfuerzo", "con mucho esfuerzo"],
    usageNote:
      "С глаголом hacer используется исчисляемо: hacer un esfuerzo por + infinitivo.",
    register: "нейтральный",
  },
  "v-b1-8": {
    partOfSpeech: "существительное",
    gender: "женский",
    forms: ["la investigación", "las investigaciones"],
    contextTranslation: "Они опубликовали новое исследование о климате.",
    collocations: ["realizar una investigación", "investigación científica"],
    usageNote:
      "Может означать и процесс исследования, и опубликованную исследовательскую работу.",
    register: "нейтрально-формальный",
  },
  "v-b1-9": {
    partOfSpeech: "существительное",
    gender: "женский",
    forms: ["la sociedad", "las sociedades"],
    contextTranslation: "Общество быстро меняется.",
    collocations: ["la sociedad actual", "vivir en sociedad"],
    usageNote:
      "В значении общества обычно употребляется в единственном числе с определённым артиклем.",
    register: "нейтральный",
  },
  "v-b1-10": {
    partOfSpeech: "существительное",
    gender: "мужской",
    forms: ["el rasgo", "los rasgos"],
    contextTranslation: "Честность — его лучшая черта.",
    collocations: ["rasgo de carácter", "rasgo distintivo"],
    usageNote:
      "Rasgo — отдельная характерная черта; característica имеет более широкое употребление.",
    register: "нейтральный",
  },
  "v-b1-11": {
    partOfSpeech: "существительное",
    gender: "мужской",
    forms: ["el acuerdo", "los acuerdos"],
    contextTranslation:
      "После нескольких часов обсуждения они пришли к соглашению.",
    collocations: ["llegar a un acuerdo", "estar de acuerdo"],
    usageNote:
      "Llegar a un acuerdo — договориться; estar de acuerdo — быть согласным.",
    register: "нейтральный",
  },
  "v-b1-12": {
    partOfSpeech: "существительное",
    gender: "мужской",
    forms: ["el suceso", "los sucesos"],
    contextTranslation: "Это было неожиданное происшествие.",
    collocations: ["un suceso inesperado", "relatar un suceso"],
    usageNote:
      "Suceso часто относится к конкретному произошедшему факту; evento может быть заранее организованным мероприятием.",
    register: "нейтрально-формальный",
  },
  "v-b1-13": {
    partOfSpeech: "существительное",
    gender: "женский",
    forms: ["la propuesta", "las propuestas"],
    contextTranslation: "Они представили интересное предложение.",
    collocations: ["hacer una propuesta", "aceptar una propuesta"],
    usageNote:
      "Propuesta — идея или план на рассмотрение; предложение как фраза — oración.",
    register: "нейтральный",
  },
  "v-b1-14": {
    partOfSpeech: "составное существительное",
    gender: "мужской",
    forms: ["el medio ambiente"],
    contextTranslation: "Мы должны заботиться об окружающей среде.",
    collocations: ["proteger el medio ambiente", "daño al medio ambiente"],
    usageNote:
      "Устойчивое сочетание обычно употребляется в единственном числе и с артиклем el.",
    register: "нейтральный",
  },
  "v-b1-15": {
    partOfSpeech: "существительное",
    gender: "мужской",
    forms: ["el empleo", "los empleos"],
    contextTranslation: "Найти стабильную работу сегодня непросто.",
    collocations: ["buscar empleo", "un empleo estable"],
    usageNote:
      "Empleo — «занятость/рабочее место» в широком смысле; trabajo — более общее «работа».",
    register: "нейтральный",
  },
  "v-b1-16": {
    partOfSpeech: "существительное",
    gender: "мужской",
    forms: ["el sueldo", "los sueldos"],
    contextTranslation:
      "Он получает хорошую зарплату, но работает много часов.",
    collocations: ["cobrar un sueldo", "un buen sueldo"],
    usageNote:
      "Sueldo — регулярная зарплата; salario — более формальный синоним, часто в юридических текстах.",
    register: "нейтральный",
  },
  "v-b1-17": {
    partOfSpeech: "существительное",
    gender: "мужской и женский",
    forms: ["el jefe", "la jefa", "los jefes"],
    contextTranslation: "Мой начальник попросил у меня отчёт к понедельнику.",
    collocations: ["el jefe de equipo", "hablar con el jefe"],
    usageNote:
      "Форма женского рода — la jefa; jefe/a — прямой руководитель, не обязательно владелец.",
    register: "нейтральный",
  },
  "v-b1-18": {
    partOfSpeech: "существительное",
    gender: "женский",
    forms: ["la entrevista", "las entrevistas"],
    contextTranslation:
      "Я нервничаю, потому что завтра у меня собеседование на работу.",
    collocations: ["una entrevista de trabajo", "hacer una entrevista"],
    usageNote:
      "Означает и собеседование при приёме на работу, и интервью в СМИ.",
    register: "нейтральный",
  },
  "v-b1-19": {
    partOfSpeech: "существительное",
    gender: "женский",
    forms: ["la huelga", "las huelgas"],
    contextTranslation: "Работники метро бастуют.",
    collocations: ["estar en huelga", "convocar una huelga"],
    usageNote:
      "Estar en huelga — «бастовать»; ir a la huelga — «выходить на забастовку».",
    register: "нейтральный",
  },
  "v-b1-20": {
    partOfSpeech: "существительное",
    gender: "женский",
    forms: ["la contaminación", "las contaminaciones"],
    contextTranslation: "Загрязнение воздуха — серьёзная проблема в городах.",
    collocations: ["la contaminación del aire", "reducir la contaminación"],
    usageNote:
      "Обычно употребляется в единственном числе; polución — менее частотный синоним.",
    register: "нейтрально-формальный",
  },
  "v-b1-21": {
    partOfSpeech: "существительное",
    gender: "мужской",
    forms: ["el reciclaje"],
    contextTranslation: "Переработка бумаги и стекла помогает планете.",
    collocations: ["el reciclaje de plástico", "fomentar el reciclaje"],
    usageNote: "Обычно неисчисляемо, в единственном числе; глагол — reciclar.",
    register: "нейтральный",
  },
  "v-b1-22": {
    partOfSpeech: "существительное",
    gender: "женский",
    forms: ["la sequía", "las sequías"],
    contextTranslation: "Этим летом была очень сильная засуха.",
    collocations: ["una sequía severa", "sufrir una sequía"],
    usageNote: "Антоним — inundación (наводнение); связано с falta de lluvia.",
    register: "нейтральный",
  },
  "v-b1-23": {
    partOfSpeech: "существительное",
    gender: "женский",
    forms: ["la pantalla", "las pantallas"],
    contextTranslation: "Он проводит слишком много часов перед экраном.",
    collocations: ["la pantalla del móvil", "el tiempo de pantalla"],
    usageNote:
      "Pantalla — экран устройства и экран в кинотеатре (la gran pantalla).",
    register: "нейтральный",
  },
  "v-b1-24": {
    partOfSpeech: "существительное",
    gender: "женский",
    forms: ["la contraseña", "las contraseñas"],
    contextTranslation: "Я забыл пароль от своей электронной почты.",
    collocations: ["cambiar la contraseña", "una contraseña segura"],
    usageNote:
      "Contraseña — пароль; синоним clave также распространён в этом значении.",
    register: "нейтральный",
  },
  "v-b1-25": {
    partOfSpeech: "существительное",
    gender: "женский",
    forms: ["la enfermedad", "las enfermedades"],
    contextTranslation: "Врач говорит, что это несерьёзная болезнь.",
    collocations: ["una enfermedad grave", "prevenir enfermedades"],
    usageNote:
      "Enfermedad — болезнь как состояние; enfermo/a — больной человек.",
    register: "нейтральный",
  },
  "v-b1-26": {
    partOfSpeech: "существительное",
    gender: "мужской",
    forms: ["el tratamiento", "los tratamientos"],
    contextTranslation: "Лечение длится две недели.",
    collocations: ["seguir un tratamiento", "un tratamiento médico"],
    usageNote:
      "Означает и медицинское лечение, и «обращение/обработку» (tratamiento de datos).",
    register: "нейтрально-формальный",
  },
  "v-b1-27": {
    partOfSpeech: "существительное",
    gender: "мужской",
    forms: ["el bienestar"],
    contextTranslation: "Спорт улучшает физическое и психическое благополучие.",
    collocations: ["el bienestar físico", "sensación de bienestar"],
    usageNote: "Неисчисляемо, обычно в единственном числе; антоним — malestar.",
    register: "нейтральный",
  },
  "v-b1-28": {
    partOfSpeech: "существительное",
    gender: "мужской и женский",
    forms: ["el ciudadano", "la ciudadana", "los ciudadanos"],
    contextTranslation: "У каждого гражданина есть права и обязанности.",
    collocations: ["los derechos del ciudadano", "un ciudadano responsable"],
    usageNote:
      "Форма женского рода — la ciudadana; ciudadanía — гражданство/совокупность граждан.",
    register: "нейтрально-формальный",
  },
  "v-b1-29": {
    partOfSpeech: "существительное",
    gender: "мужской",
    forms: ["el gobierno", "los gobiernos"],
    contextTranslation: "Правительство объявило о новых экономических мерах.",
    collocations: ["el gobierno central", "formar gobierno"],
    usageNote:
      "Gobierno — орган власти; gobernar — глагол «управлять, править».",
    register: "нейтрально-формальный",
  },
  "v-b1-30": {
    partOfSpeech: "существительное",
    gender: "женский",
    forms: ["la ley", "las leyes"],
    contextTranslation: "Новый закон вступает в силу в следующем году.",
    collocations: ["aprobar una ley", "cumplir la ley"],
    usageNote:
      "Множественное число — leyes; entrar en vigor — «вступать в силу».",
    register: "нейтрально-формальный",
  },
  "v-b1-31": {
    partOfSpeech: "существительное",
    gender: "мужской",
    forms: ["el desarrollo", "los desarrollos"],
    contextTranslation:
      "Технологии способствуют экономическому развитию страны.",
    collocations: ["el desarrollo económico", "el desarrollo sostenible"],
    usageNote: "Desarrollo — развитие/разработка; глагол — desarrollar(se).",
    register: "нейтрально-формальный",
  },
  "v-b1-32": {
    partOfSpeech: "существительное",
    gender: "женский",
    forms: ["la encuesta", "las encuestas"],
    contextTranslation: "По данным недавнего опроса, большинство «за».",
    collocations: ["hacer una encuesta", "según una encuesta"],
    usageNote:
      "Encuesta — соцопрос; не путать с examen (экзамен) или prueba (тест).",
    register: "нейтрально-формальный",
  },
  "v-b1-33": {
    partOfSpeech: "глагол",
    forms: ["lograr", "logro", "logró", "logrado"],
    contextTranslation: "Ценой усилий он сумел сдать все экзамены.",
    collocations: ["lograr un objetivo", "lograr hacer algo"],
    usageNote:
      "Lograr + infinitivo — «суметь/добиться сделать»; близко к conseguir.",
    register: "нейтральный",
  },
  "v-b1-34": {
    partOfSpeech: "глагол",
    forms: ["mejorar", "mejoro", "mejoró", "mejorado"],
    contextTranslation:
      "В этом году он хочет улучшить свой уровень испанского.",
    collocations: ["mejorar el nivel", "mejorar la situación"],
    usageNote:
      "Переходный (mejorar algo) и непереходный (el tiempo mejora); антоним — empeorar.",
    register: "нейтральный",
  },
  "v-b1-35": {
    partOfSpeech: "глагол",
    forms: ["desarrollar", "desarrollo", "desarrolló", "desarrollado"],
    contextTranslation: "Компания хочет разработать новое приложение.",
    collocations: ["desarrollar una idea", "desarrollar un proyecto"],
    usageNote:
      "Desarrollarse (возвратно) — «развиваться, происходить»: la reunión se desarrolló bien.",
    register: "нейтральный",
  },
  "v-b1-36": {
    partOfSpeech: "глагол",
    forms: ["quejarse", "me quejo", "se quejan", "se quejó"],
    contextTranslation: "Соседи жалуются на шум по ночам.",
    collocations: ["quejarse de algo", "quejarse por todo"],
    usageNote: "Возвратный, управляет предлогом de: quejarse de algo.",
    register: "нейтральный",
  },
  "v-b1-37": {
    partOfSpeech: "глагол",
    forms: ["aumentar", "aumenta", "aumentó", "aumentado"],
    contextTranslation: "Цена на жильё сильно выросла.",
    collocations: ["aumentar el precio", "aumentar considerablemente"],
    usageNote:
      "Переходный и непереходный; антоним — disminuir. Часто с наречиями степени.",
    register: "нейтрально-формальный",
  },
  "v-b1-38": {
    partOfSpeech: "глагол",
    forms: ["disminuir", "disminuye", "disminuyó", "disminuido"],
    contextTranslation: "В этом году число аварий сократилось.",
    collocations: ["disminuir el riesgo", "disminuir poco a poco"],
    usageNote:
      "В настоящем времени добавляет y: disminuye, disminuyen; антоним — aumentar.",
    register: "нейтрально-формальный",
  },
  "v-b1-39": {
    partOfSpeech: "глагол",
    forms: ["exigir", "exijo", "exige", "exigió"],
    contextTranslation: "Студенты требуют чёткого ответа.",
    collocations: ["exigir una respuesta", "exigir responsabilidades"],
    usageNote: "В 1-м лице presente — exijo (g→j); exigir que + subjuntivo.",
    register: "нейтрально-формальный",
  },
  "v-b1-40": {
    partOfSpeech: "глагол",
    forms: ["compartir", "comparto", "comparte", "compartió"],
    contextTranslation: "Мне нравится делиться своими идеями с группой.",
    collocations: ["compartir un piso", "compartir una opinión"],
    usageNote:
      "Compartir algo con alguien; в соцсетях — «поделиться (репостнуть)».",
    register: "нейтральный",
  },
  "v-b1-41": {
    partOfSpeech: "глагол",
    forms: ["apoyar", "apoyo", "apoya", "apoyó"],
    contextTranslation: "Моя семья всегда поддерживает меня в моих решениях.",
    collocations: ["apoyar a alguien", "apoyar una decisión"],
    usageNote:
      "Apoyar a alguien — поддерживать (перед одушевлённым — предлог a); apoyarse en — опираться на.",
    register: "нейтральный",
  },
  "v-b1-42": {
    partOfSpeech: "глагол",
    forms: ["atreverse", "me atrevo", "se atreve", "se atrevió"],
    contextTranslation: "Он не решается выступать на публике.",
    collocations: ["atreverse a hacer algo", "no atreverse a decir"],
    usageNote: "Возвратный; управляет предлогом a: atreverse a + infinitivo.",
    register: "нейтральный",
  },
  "v-b1-43": {
    partOfSpeech: "прилагательное",
    forms: ["imprescindible", "imprescindibles"],
    contextTranslation: "Для этой должности обязательно знать английский.",
    collocations: ["es imprescindible", "un requisito imprescindible"],
    usageNote:
      "Одна форма для мужского и женского рода; усиливает «необходимость» сильнее, чем necesario.",
    register: "нейтрально-формальный",
  },
  "v-b1-44": {
    partOfSpeech: "прилагательное",
    forms: ["asequible", "asequibles"],
    contextTranslation: "Мы ищем квартиру по доступной цене.",
    collocations: ["un precio asequible", "una vivienda asequible"],
    usageNote:
      "О цене — «доступный по деньгам»; accesible скорее «доступный физически/понятный».",
    register: "нейтральный",
  },
  "v-b1-45": {
    partOfSpeech: "прилагательное",
    forms: ["exitoso", "exitosa", "exitosos", "exitosas"],
    contextTranslation: "Это была очень успешная кампания.",
    collocations: ["una empresa exitosa", "un proyecto exitoso"],
    usageNote: "Согласуется в роде и числе; образовано от éxito (успех).",
    register: "нейтральный",
  },
  "v-b1-46": {
    partOfSpeech: "прилагательное",
    forms: ["cotidiano", "cotidiana", "cotidianos", "cotidianas"],
    contextTranslation: "Мобильный телефон стал частью повседневной жизни.",
    collocations: ["la vida cotidiana", "una tarea cotidiana"],
    usageNote:
      "Часто в сочетании la vida cotidiana; синоним diario, но diario ещё и «дневник/газета».",
    register: "нейтральный",
  },
  "v-b1-47": {
    partOfSpeech: "прилагательное",
    forms: ["sostenible", "sostenibles"],
    contextTranslation: "Они делают ставку на более экологичный туризм.",
    collocations: ["el desarrollo sostenible", "un modelo sostenible"],
    usageNote:
      "Одна форма для обоих родов; часто в контексте экологии и экономики.",
    register: "нейтрально-формальный",
  },
  "v-b1-48": {
    partOfSpeech: "прилагательное",
    forms: ["eficaz", "eficaces"],
    contextTranslation: "Это очень эффективный способ запоминать слова.",
    collocations: ["un método eficaz", "un remedio eficaz"],
    usageNote:
      "Eficaz — даёт нужный результат; eficiente — с меньшими затратами. Множественное — eficaces.",
    register: "нейтрально-формальный",
  },
  "v-b1-49": {
    partOfSpeech: "предложный оборот",
    forms: ["a pesar de", "a pesar de que"],
    contextTranslation: "Несмотря на дождь, мы вышли гулять.",
    collocations: ["a pesar de todo", "a pesar de que + verbo"],
    usageNote:
      "A pesar de + существительное/инфинитив; a pesar de que + спрягаемый глагол.",
    register: "нейтральный",
  },
  "v-b1-50": {
    partOfSpeech: "союзный оборот",
    forms: ["por lo tanto"],
    contextTranslation: "Он не учился, поэтому провалил экзамен.",
    collocations: ["por lo tanto, ...", "y, por lo tanto, ..."],
    usageNote:
      "Вводит следствие; обычно выделяется запятыми. Синонимы: por eso, así que.",
    register: "нейтрально-формальный",
  },
};

export const b1Vocabulary = b1VocabularyBase.map((card) => ({
  ...card,
  ...b1VocabularyDetails[card.id],
})) satisfies VocabularyCard[];
