import type { VocabularyCard } from "../../types";

export const b1Vocabulary = [
  {
    id: "v-b1-1",
    level: "B1",
    word: "logro",
    translation: "достижение",
    accept: ["достижение"],
    context: "Graduarse fue un gran logro para ella.",
    revision: 1,
  },
  {
    id: "v-b1-2",
    level: "B1",
    word: "desafío",
    translation: "вызов",
    accept: ["вызов", "трудность"],
    context: "Aprender un idioma nuevo es un desafío.",
    revision: 1,
  },
  {
    id: "v-b1-3",
    level: "B1",
    word: "ventaja",
    translation: "преимущество",
    accept: ["преимущество", "плюс"],
    context: "Trabajar desde casa tiene muchas ventajas.",
    revision: 1,
  },
  {
    id: "v-b1-4",
    level: "B1",
    word: "desventaja",
    translation: "недостаток",
    accept: ["недостаток", "минус"],
    context: "Esa decisión también tiene desventajas.",
    revision: 1,
  },
  {
    id: "v-b1-5",
    level: "B1",
    word: "objetivo",
    translation: "цель",
    accept: ["цель"],
    context: "Mi objetivo es aprender español en un año.",
    revision: 1,
  },
  {
    id: "v-b1-6",
    level: "B1",
    word: "herramienta",
    translation: "инструмент",
    accept: ["инструмент"],
    context: "Internet es una herramienta muy útil.",
    revision: 1,
  },
  {
    id: "v-b1-7",
    level: "B1",
    word: "esfuerzo",
    translation: "усилие",
    accept: ["усилие", "старание"],
    context: "Consiguió el trabajo con mucho esfuerzo.",
    revision: 1,
  },
  {
    id: "v-b1-8",
    level: "B1",
    word: "investigación",
    translation: "исследование",
    accept: ["исследование"],
    context: "Publicaron una nueva investigación sobre el clima.",
    revision: 1,
  },
  {
    id: "v-b1-9",
    level: "B1",
    word: "sociedad",
    translation: "общество",
    accept: ["общество"],
    context: "La sociedad está cambiando rápidamente.",
    revision: 1,
  },
  {
    id: "v-b1-10",
    level: "B1",
    word: "rasgo",
    translation: "черта",
    accept: ["черта", "особенность"],
    context: "La honestidad es su mejor rasgo.",
    revision: 1,
  },
  {
    id: "v-b1-11",
    level: "B1",
    word: "acuerdo",
    translation: "соглашение",
    accept: ["соглашение", "договорённость"],
    context: "Llegaron a un acuerdo después de horas de debate.",
    revision: 1,
  },
  {
    id: "v-b1-12",
    level: "B1",
    word: "suceso",
    translation: "событие",
    accept: ["событие", "происшествие"],
    context: "Fue un suceso inesperado.",
    revision: 1,
  },
  {
    id: "v-b1-13",
    level: "B1",
    word: "propuesta",
    translation: "предложение",
    accept: ["предложение"],
    context: "Presentaron una propuesta interesante.",
    revision: 1,
  },
  {
    id: "v-b1-14",
    level: "B1",
    word: "medio ambiente",
    translation: "окружающая среда",
    accept: ["окружающая среда", "экология"],
    context: "Debemos cuidar el medio ambiente.",
    revision: 1,
  },
] satisfies VocabularyCard[];
