import type { ConjugationCard } from "../../types";

export const c1Conjugations = [
  {
    id: "cj-c1-1",
    level: "C1",
    verb: "hablar",
    verbMeaning: "говорить",
    tense: "condicional-compuesto",
    tenseLabel: "Condicional compuesto",
    forms: [
      "habría hablado",
      "habrías hablado",
      "habría hablado",
      "habríamos hablado",
      "habríais hablado",
      "habrían hablado",
    ],
    example: {
      es: "Yo habría hablado con él si hubiera tenido la oportunidad.",
      ru: "Я бы поговорил с ним, если бы у меня была возможность.",
    },
    revision: 1,
  },
  {
    id: "cj-c1-2",
    level: "C1",
    verb: "tener",
    verbMeaning: "иметь",
    tense: "subj-pluscuamperfecto",
    tenseLabel: "Subjuntivo pluscuamperfecto",
    forms: [
      "hubiera tenido",
      "hubieras tenido",
      "hubiera tenido",
      "hubiéramos tenido",
      "hubierais tenido",
      "hubieran tenido",
    ],
    example: {
      es: "Ojalá hubiera tenido más paciencia entonces.",
      ru: "Хоть бы у меня тогда было больше терпения.",
    },
    revision: 1,
  },
  {
    id: "cj-c1-3",
    level: "C1",
    verb: "ir",
    verbMeaning: "идти, ехать",
    tense: "condicional-compuesto",
    tenseLabel: "Condicional compuesto",
    forms: [
      "habría ido",
      "habrías ido",
      "habría ido",
      "habríamos ido",
      "habríais ido",
      "habrían ido",
    ],
    example: {
      es: "Habríamos ido a la playa si hubiera hecho sol.",
      ru: "Мы бы поехали на пляж, если бы было солнечно.",
    },
    revision: 1,
  },
  {
    id: "cj-c1-4",
    level: "C1",
    verb: "ser",
    verbMeaning: "быть",
    tense: "subj-pluscuamperfecto",
    tenseLabel: "Subjuntivo pluscuamperfecto",
    forms: [
      "hubiera sido",
      "hubieras sido",
      "hubiera sido",
      "hubiéramos sido",
      "hubierais sido",
      "hubieran sido",
    ],
    example: {
      es: "Si hubiera sido más valiente, habría aceptado el reto.",
      ru: "Если бы я был смелее, я бы принял вызов.",
    },
    revision: 1,
  },
  {
    id: "cj-c1-5",
    level: "C1",
    verb: "poder",
    verbMeaning: "мочь",
    tense: "condicional-compuesto",
    tenseLabel: "Condicional compuesto",
    forms: [
      "habría podido",
      "habrías podido",
      "habría podido",
      "habríamos podido",
      "habríais podido",
      "habrían podido",
    ],
    example: {
      es: "Habría podido terminar antes si me hubieran ayudado.",
      ru: "Я бы смог закончить раньше, если бы мне помогли.",
    },
    revision: 1,
  },
  {
    id: "cj-c1-6",
    level: "C1",
    verb: "comer",
    verbMeaning: "есть, кушать",
    tense: "subj-pluscuamperfecto",
    tenseLabel: "Subjuntivo pluscuamperfecto",
    forms: [
      "hubiera comido",
      "hubieras comido",
      "hubiera comido",
      "hubiéramos comido",
      "hubierais comido",
      "hubieran comido",
    ],
    example: {
      es: "Dudaba que hubieran comido algo tan raro.",
      ru: "Он сомневался, что они ели что-то настолько странное.",
    },
    revision: 1,
  },
] satisfies ConjugationCard[];
