import type { GrammarExercise } from "../../types";

export const c1Grammar = [
  {
    id: "c1-01",
    level: "C1",
    topic: "concesivas complejas",
    type: "mcq",
    prompt: "Por más que lo ___, no consigo entenderlo.",
    options: ["intento", "intentaré", "intentaba", "intentara"],
    answer: "intento",
    explain:
      '"Por más que" с реальным, фактическим значением требует indicativo: por más que lo intento (несмотря на то, что действительно пытаюсь).',
    revision: 1,
  },
  {
    id: "c1-02",
    level: "C1",
    topic: "por / para avanzado",
    type: "mcq",
    prompt: "Lo tomaron ___ un experto, aunque apenas sabía nada.",
    options: ["por", "para", "como", "de"],
    answer: "por",
    explain:
      '"Tomar/confundir por" — устойчивое выражение "принять за (кого-то)": lo tomaron por un experto.',
    revision: 1,
  },
  {
    id: "c1-03",
    level: "C1",
    topic: "perífrasis verbales",
    type: "mcq",
    prompt: "___ dos años estudiando chino y todavía no domino los caracteres.",
    options: ["Llevo", "Estoy", "Voy", "Tengo"],
    answer: "llevo",
    explain:
      '"Llevar + periodo de tiempo + gerundio" выражает длительность действия, продолжающегося до сих пор: llevo dos años estudiando.',
    revision: 1,
  },
  {
    id: "c1-04",
    level: "C1",
    topic: "perífrasis verbales",
    type: "mcq",
    prompt: "No me hables de eso otra vez, ya ___ de decírtelo mil veces.",
    options: ["acabo", "vuelvo", "dejo", "llevo"],
    answer: "acabo",
    explain:
      '"Acabar de + infinitivo" означает "только что что-то сделать": acabo de decírtelo — я только что тебе это сказал.',
    revision: 1,
  },
  {
    id: "c1-05",
    level: "C1",
    topic: "estructuras enfáticas",
    type: "mcq",
    prompt: "No te imaginas ___ difícil que fue tomar esa decisión.",
    options: ["lo", "que", "cuán", "el"],
    answer: "lo",
    explain:
      'Эмфатическая конструкция "lo + прилагательное + que" усиливает степень признака: lo difícil que fue = "насколько это было трудно".',
    revision: 1,
  },
  {
    id: "c1-06",
    level: "C1",
    topic: "subjuntivo relativo indefinido",
    type: "mcq",
    prompt: "Busco un asistente que ___ hablar tres idiomas.",
    options: ["sepa", "sabe", "sabrá", "supo"],
    answer: "sepa",
    explain:
      'Когда антецедент неопределённый/несуществующий ("un asistente" — ещё не найденный), придаточное относительное требует subjuntivo: que sepa.',
    revision: 1,
  },
  {
    id: "c1-07",
    level: "C1",
    topic: "nominalización / registro formal",
    type: "mcq",
    prompt: "La empresa comunicó ___ decisión de cerrar la planta.",
    options: ["su", "la", "una", "esta la"],
    answer: "su",
    explain:
      'В формальном регистре часто используется номинализация действия: "comunicar su decisión" (существительное вместо глагольной фразы) звучит более официально.',
    revision: 1,
  },
  {
    id: "c1-08",
    level: "C1",
    topic: "conectores discursivos",
    type: "mcq",
    prompt:
      "El proyecto fue costoso; ___, los resultados justificaron la inversión.",
    options: ["no obstante", "porque", "ya que", "si bien"],
    answer: "no obstante",
    explain:
      '"No obstante" (тем не менее) вводит противопоставление между двумя утверждениями, аналогично "sin embargo".',
    revision: 1,
  },
  {
    id: "c1-09",
    level: "C1",
    topic: "pasiva refleja vs ser",
    type: "mcq",
    prompt: "___ construyeron tres nuevos hospitales el año pasado.",
    options: ["Se", "Fueron", "Son", "Están"],
    answer: "se",
    explain:
      'Пассивная возвратная конструкция "se + verbo" часто предпочтительнее пассива с "ser", когда субъект неважен и объект — предмет: se construyeron tres hospitales.',
    revision: 1,
  },
  {
    id: "c1-10",
    level: "C1",
    topic: "colocaciones",
    type: "mcq",
    prompt: "Se ___ cuenta de su error demasiado tarde.",
    options: ["dio", "hizo", "tomó", "llevó"],
    answer: "dio",
    explain:
      '"Darse cuenta de algo" — устойчивое выражение "осознать что-либо": se dio cuenta de su error.',
    revision: 1,
  },
  {
    id: "c1-11",
    level: "C1",
    topic: "discurso indirecto complejo",
    type: "mcq",
    prompt: "Dijo que, si ___ tiempo, habría terminado el informe.",
    options: ["hubiera tenido", "tenía", "tuviera", "tuvo"],
    answer: "hubiera tenido",
    explain:
      "В сложной косвенной речи при нереальном условии в прошлом сохраняется pluscuamperfecto de subjuntivo: si hubiera tenido tiempo.",
    revision: 1,
  },
  {
    id: "c1-12",
    level: "C1",
    topic: "sea como sea",
    type: "mcq",
    prompt: "___ , terminaremos el proyecto a tiempo.",
    options: [
      "Sea como sea",
      "Sea que sea",
      "Como si fuera",
      "Fuera como fuera antes",
    ],
    answer: "sea como sea",
    explain:
      '"Sea como sea" — устойчивое выражение "как бы то ни было / во что бы то ни стало", часто в начале фразы для усиления решимости.',
    revision: 1,
  },
  {
    id: "c1-13",
    level: "C1",
    topic: "concesivas — por muy...que",
    type: "fill",
    prompt: "Por muy difícil que (ser) ___, lo lograremos.",
    answer: "sea",
    explain:
      '"Por muy + прилагательное + que" всегда требует subjuntivo, независимо от реальности ситуации.',
    revision: 1,
  },
  {
    id: "c1-14",
    level: "C1",
    topic: "perífrasis — volver a",
    type: "fill",
    prompt: "No quiero (volver a/cometer) ___ ___ el mismo error.",
    answer: "volver a cometer",
    explain:
      '"Volver a + infinitivo" означает "сделать что-то снова": volver a cometer = совершить ещё раз.',
    revision: 1,
  },
  {
    id: "c1-15",
    level: "C1",
    topic: "nominalización",
    type: "fill",
    prompt: "La ___ (decidir) de cerrar la fábrica sorprendió a todos.",
    answer: "decisión",
    explain:
      "В формальном регистре глагол часто превращается в существительное (nominalización): decidir → la decisión.",
    revision: 1,
  },
  {
    id: "c1-16",
    level: "C1",
    topic: "conectores discursivos",
    type: "fill",
    prompt: "El plan era arriesgado; ___, decidieron seguir adelante.",
    answer: "sin embargo",
    explain:
      '"Sin embargo" — коннектор противопоставления, синонимичный "no obstante" (тем не менее).',
    revision: 1,
  },
  {
    id: "c1-17",
    level: "C1",
    topic: "pasiva refleja",
    type: "fill",
    prompt: "___ (vender) muchos coches usados en esta tienda.",
    answer: "se venden",
    explain:
      'Пассивная возвратная конструкция "se + глагол" согласуется в числе с подлежащим (coches — мн.ч.): se venden.',
    revision: 1,
  },
  {
    id: "c1-18",
    level: "C1",
    topic: "colocaciones",
    type: "fill",
    prompt:
      "Al escuchar la noticia, se ___ (dar) cuenta de que había cometido un error.",
    answer: "dio",
    explain:
      '"Darse cuenta de algo" = осознать что-либо. Претерит от dar (3 л. ед.ч.): dio.',
    revision: 1,
  },
  {
    id: "c1-19",
    level: "C1",
    topic: "discurso indirecto",
    type: "fill",
    prompt: "Me dijo que (venir) ___ tan pronto como pudiera.",
    answer: "vendría",
    explain:
      "В косвенной речи после глагола в прошедшем времени futuro переходит в condicional: vendrá → vendría.",
    revision: 1,
  },
  {
    id: "c1-20",
    level: "C1",
    topic: "subjuntivo — antecedente negado",
    type: "fill",
    prompt: "No hay nadie que (saber) ___ resolver este acertijo.",
    answer: "sepa",
    explain:
      'Когда антецедент отрицается ("nadie"), придаточное относительное требует subjuntivo: que sepa.',
    revision: 1,
  },
  {
    id: "c1-21",
    level: "C1",
    topic: "estructuras enfáticas",
    type: "fill",
    prompt: "Fue precisamente entonces ___ comprendí todo.",
    answer: "cuando",
    explain:
      'Конструкция "fue... cuando" (эмфатическое выделение) используется для акцента на моменте времени.',
    revision: 1,
  },
  {
    id: "c1-22",
    level: "C1",
    topic: "por / para avanzado",
    type: "fill",
    prompt: "Lo hizo ___ despecho, no por amor.",
    answer: "por",
    explain:
      '"Por" указывает причину/мотив действия: lo hizo por despecho (сделал это из злости/обиды).',
    revision: 1,
  },
] satisfies GrammarExercise[];
