import type { VocabularyCard } from "../../types";

export const c1Vocabulary = [
  {
    id: "v-c1-1",
    level: "C1",
    word: "idiosincrasia",
    translation: "самобытность",
    accept: ["самобытность", "особенность характера"],
    context: "Cada país tiene su propia idiosincrasia.",
    revision: 1,
  },
  {
    id: "v-c1-2",
    level: "C1",
    word: "controvertido",
    translation: "спорный",
    accept: ["спорный"],
    context: "Es un tema muy controvertido.",
    revision: 1,
  },
  {
    id: "v-c1-3",
    level: "C1",
    word: "paulatino",
    translation: "постепенный",
    accept: ["постепенный"],
    context: "Se observa un declive paulatino en las ventas.",
    revision: 1,
  },
  {
    id: "v-c1-4",
    level: "C1",
    word: "contundente",
    translation: "убедительный",
    accept: ["убедительный", "весомый"],
    context: "Presentó pruebas contundentes.",
    revision: 1,
  },
  {
    id: "v-c1-5",
    level: "C1",
    word: "desasosiego",
    translation: "беспокойство",
    accept: ["беспокойство", "тревога"],
    context: "Sintió un profundo desasosiego.",
    revision: 1,
  },
  {
    id: "v-c1-6",
    level: "C1",
    word: "pormenor",
    translation: "подробность",
    accept: ["подробность", "деталь"],
    context: "Explicó todos los pormenores del acuerdo.",
    revision: 1,
  },
  {
    id: "v-c1-7",
    level: "C1",
    word: "arraigado",
    translation: "укоренившийся",
    accept: ["укоренившийся"],
    context: "Es una tradición muy arraigada en la cultura.",
    revision: 1,
  },
  {
    id: "v-c1-8",
    level: "C1",
    word: "vislumbrar",
    translation: "предвидеть",
    accept: ["предвидеть", "смутно различать"],
    context: "Empezaba a vislumbrar una solución.",
    revision: 1,
  },
  {
    id: "v-c1-9",
    level: "C1",
    word: "encauzar",
    translation: "направлять",
    accept: ["направлять"],
    context: "Intentaron encauzar el debate hacia soluciones prácticas.",
    revision: 1,
  },
  {
    id: "v-c1-10",
    level: "C1",
    word: "ineludible",
    translation: "неизбежный",
    accept: ["неизбежный"],
    context: "Es una responsabilidad ineludible.",
    revision: 1,
  },
  {
    id: "v-c1-11",
    level: "C1",
    word: "desentrañar",
    translation: "разгадать",
    accept: ["разгадать", "распутать"],
    context: "Los científicos intentan desentrañar el misterio.",
    revision: 1,
  },
  {
    id: "v-c1-12",
    level: "C1",
    word: "sopesar",
    translation: "взвешивать",
    accept: ["взвешивать"],
    context: "Hay que sopesar los pros y los contras.",
    revision: 1,
  },
  {
    id: "v-c1-13",
    level: "C1",
    word: "reticente",
    translation: "несклонный",
    accept: ["несклонный", "сдержанный"],
    context: "Se mostró reticente a aceptar el cambio.",
    revision: 1,
  },
  {
    id: "v-c1-14",
    level: "C1",
    word: "subyacente",
    translation: "лежащий в основе",
    accept: ["лежащий в основе", "подспудный"],
    context: "Hay un problema subyacente que nadie menciona.",
    revision: 1,
  },
] satisfies VocabularyCard[];
