import type { GrammarExercise } from "../../types";

export const a1Grammar = [
  {
    id: "a1-01",
    level: "A1",
    topic: "ser / estar",
    type: "mcq",
    prompt: "Ella ___ profesora.",
    options: ["es", "está", "son", "están"],
    answer: "es",
    explain:
      "<b>Ser</b> идентифицирует человека или относит его к категории: профессии, национальности, происхождению. Поэтому «Ella <b>es</b> profesora». Критерий «постоянное/временное» — только начальная подсказка и не заменяет это правило.",
    revision: 1,
  },
  {
    id: "a1-02",
    level: "A1",
    topic: "ser / estar",
    type: "mcq",
    prompt: "Nosotros ___ muy cansados hoy.",
    options: ["somos", "estamos", "es", "está"],
    answer: "estamos",
    explain:
      "<b>Estar</b> описывает состояние человека в конкретной ситуации; маркер hoy подчёркивает текущее состояние: estamos cansados.",
    revision: 1,
  },
  {
    id: "a1-03",
    level: "A1",
    topic: "artículos",
    type: "mcq",
    prompt: "___ agua está fría.",
    options: ["La", "El", "Los", "Las"],
    answer: "el",
    explain:
      'Слово "agua" женского рода, но начинается на ударную "a", поэтому в единственном числе перед ним ставится артикль <b>el</b> (el agua), хотя прилагательные согласуются в женском роде: el agua fría.',
    revision: 1,
  },
  {
    id: "a1-04",
    level: "A1",
    topic: "artículos",
    type: "mcq",
    prompt: "Tengo ___ hermano y ___ hermana.",
    options: ["un / una", "una / un", "el / la", "un / uno"],
    answer: "un / una",
    solvedExample: "Tengo un hermano y una hermana.",
    explain:
      'Неопределённый артикль: <b>un</b> для мужского рода, <b>una</b> для женского. "Hermano" — м.р., "hermana" — ж.р.',
    revision: 1,
  },
  {
    id: "a1-05",
    level: "A1",
    topic: "presente -ar",
    type: "fill",
    prompt: "Yo (hablar) ___ español todos los días.",
    answer: "hablo",
    explain:
      'Глаголы на -ar в настоящем времени: habl<b>o</b>, hablas, habla, hablamos, habláis, hablan. Для "yo" окончание -o.',
    revision: 1,
  },
  {
    id: "a1-06",
    level: "A1",
    topic: "presente -er",
    type: "fill",
    prompt: "Tú (comer) ___ mucha fruta.",
    answer: "comes",
    explain:
      'Глаголы на -er: com<b>o</b>, com<b>es</b>, come, comemos, coméis, comen. Для "tú" окончание -es.',
    revision: 1,
  },
  {
    id: "a1-07",
    level: "A1",
    topic: "presente -ir",
    type: "fill",
    prompt: "Ellos (vivir) ___ en Madrid.",
    answer: "viven",
    explain:
      'Глаголы на -ir: vivo, vives, vive, vivimos, vivís, viv<b>en</b>. Для "ellos/ellas" окончание -en.',
    revision: 1,
  },
  {
    id: "a1-08",
    level: "A1",
    topic: "verbo tener",
    type: "mcq",
    prompt: "¿Cuántos años ___ tú?",
    options: ["tienes", "tienen", "tengo", "tenéis"],
    answer: "tienes",
    explain:
      'Tener — неправильный глагол: tengo, <b>tienes</b>, tiene, tenemos, tenéis, tienen. Для "tú" — tienes.',
    revision: 1,
  },
  {
    id: "a1-09",
    level: "A1",
    topic: "ir + a",
    type: "mcq",
    prompt: "Mañana ___ a visitar a mis abuelos.",
    options: ["voy", "va", "vamos", "van"],
    answer: "voy",
    explain:
      'Конструкция "ir + a + инфинитив" выражает ближайшее будущее. Для "yo" форма глагола ir — <b>voy</b>: voy a visitar.',
    revision: 1,
  },
  {
    id: "a1-10",
    level: "A1",
    topic: "posesivos",
    type: "mcq",
    prompt: "Este es ___ coche (de nosotros).",
    options: ["nuestro", "su", "tu", "mi"],
    answer: "nuestro",
    explain:
      'Притяжательное местоимение для "мы" — <b>nuestro/nuestra/nuestros/nuestras</b>, согласуется с существительным: nuestro coche (м.р. ед.ч.).',
    revision: 1,
  },
  {
    id: "a1-11",
    level: "A1",
    topic: "gustar",
    type: "mcq",
    prompt: "A mí ___ los gatos.",
    options: ["me gustan", "me gusta", "le gustan", "les gusta"],
    answer: "me gustan",
    explain:
      'Глагол "gustar" согласуется с тем, что нравится, а не с человеком. "Los gatos" — мн.ч., поэтому <b>gustan</b>; "a mí" требует местоимения <b>me</b>.',
    revision: 1,
  },
  {
    id: "a1-12",
    level: "A1",
    topic: "plural",
    type: "fill",
    prompt: 'singular: "el lápiz" → plural: "los ___"',
    answer: "lápices",
    explain:
      "Существительные, оканчивающиеся на -z, во множественном числе меняют z на c и добавляют -es: lápiz → lápices.",
    revision: 1,
  },
  {
    id: "a1-13",
    level: "A1",
    topic: "adjetivos — género",
    type: "mcq",
    prompt: "Mi casa es muy ___.",
    options: ["bonita", "bonito", "bonitos", "bonitas"],
    answer: "bonita",
    explain:
      'Прилагательные согласуются в роде и числе с существительным. "Casa" — женский род, единственное число → bonita.',
    revision: 1,
  },
  {
    id: "a1-14",
    level: "A1",
    topic: "ser / estar",
    type: "mcq",
    prompt: "El libro ___ en la mesa.",
    options: ["está", "es", "están", "son"],
    answer: "está",
    explain:
      "Для местоположения предметов всегда используется <b>estar</b>: el libro está en la mesa.",
    revision: 1,
  },
  {
    id: "a1-15",
    level: "A1",
    topic: "presente -ar",
    type: "fill",
    prompt: "Ella (trabajar) ___ en un banco.",
    answer: "trabaja",
    explain:
      "Глаголы на -ar, 3-е лицо ед.ч.: trabaj<b>a</b>. Окончания: -o, -as, -a, -amos, -áis, -an.",
    revision: 1,
  },
  {
    id: "a1-16",
    level: "A1",
    topic: "presente ser",
    type: "fill",
    prompt: "Nosotros (ser) ___ estudiantes.",
    answer: "somos",
    explain: "Глагол ser неправильный: soy, eres, es, <b>somos</b>, sois, son.",
    revision: 1,
  },
  {
    id: "a1-17",
    level: "A1",
    topic: "hay",
    type: "fill",
    prompt: "En la clase (haber) ___ veinte alumnos.",
    answer: "hay",
    explain:
      '"Hay" — безличная неизменяемая форма глагола haber, означает "есть/имеется", используется и в единственном, и во множественном числе.',
    revision: 1,
  },
  {
    id: "a1-18",
    level: "A1",
    topic: "posesivos",
    type: "fill",
    prompt: "Este es ___ perro (de ella).",
    answer: "su",
    explain:
      '"Su" означает "его/её/их" и не меняется в зависимости от рода обладателя, а согласуется только с числом предмета: su perro, sus perros.',
    revision: 1,
  },
  {
    id: "a1-19",
    level: "A1",
    topic: "plural",
    type: "fill",
    prompt: 'singular: "la ciudad" → plural: "las ___"',
    answer: "ciudades",
    explain:
      "Существительные, оканчивающиеся на согласную, образуют множественное число добавлением -es: ciudad → ciudades.",
    revision: 1,
  },
  {
    id: "a1-20",
    level: "A1",
    topic: "presente -ir",
    type: "fill",
    prompt: "Yo (escribir) ___ una carta.",
    answer: "escribo",
    explain:
      "Глаголы на -ir, 1-е лицо ед.ч.: escrib<b>o</b>. Окончания: -o, -es, -e, -imos, -ís, -en.",
    revision: 1,
  },
] satisfies GrammarExercise[];
