import type { VocabularyCard } from "../../types";

export const a1Vocabulary = [
  {
    id: "v-a1-1",
    level: "A1",
    word: "casa",
    translation: "дом",
    accept: ["дом", "домик"],
    context: "Mi casa está cerca del parque.",
    contextTarget: "casa",
    revision: 1,
  },
  {
    id: "v-a1-2",
    level: "A1",
    word: "amigo",
    translation: "друг",
    accept: ["друг", "приятель"],
    context: "Mi amigo vive en Madrid.",
    contextTarget: "amigo",
    revision: 1,
  },
  {
    id: "v-a1-3",
    level: "A1",
    word: "comida",
    translation: "еда",
    accept: ["еда", "пища"],
    context: "La comida está muy rica.",
    contextTarget: "comida",
    revision: 1,
  },
  {
    id: "v-a1-4",
    level: "A1",
    word: "trabajo",
    translation: "работа",
    accept: ["работа"],
    context: "Tengo mucho trabajo hoy.",
    contextTarget: "trabajo",
    revision: 1,
  },
  {
    id: "v-a1-5",
    level: "A1",
    word: "agua",
    translation: "вода",
    accept: ["вода"],
    context: "Necesito un vaso de agua.",
    contextTarget: "agua",
    revision: 1,
  },
  {
    id: "v-a1-6",
    level: "A1",
    word: "libro",
    translation: "книга",
    accept: ["книга"],
    context: "Este libro es muy interesante.",
    contextTarget: "libro",
    revision: 1,
  },
  {
    id: "v-a1-7",
    level: "A1",
    word: "día",
    translation: "день",
    accept: ["день"],
    context: "Hoy es un buen día.",
    contextTarget: "día",
    revision: 1,
  },
  {
    id: "v-a1-8",
    level: "A1",
    word: "noche",
    translation: "ночь",
    accept: ["ночь"],
    context: "Por la noche veo la televisión.",
    contextTarget: "noche",
    revision: 1,
  },
  {
    id: "v-a1-9",
    level: "A1",
    word: "ciudad",
    translation: "город",
    accept: ["город"],
    context: "Vivo en una ciudad grande.",
    contextTarget: "ciudad",
    revision: 1,
  },
  {
    id: "v-a1-10",
    level: "A1",
    word: "tiempo",
    translation: "время",
    accept: ["время", "погода"],
    context: "No tengo tiempo para eso.",
    contextTarget: "tiempo",
    revision: 1,
  },
  {
    id: "v-a1-11",
    level: "A1",
    word: "familia",
    translation: "семья",
    accept: ["семья"],
    context: "Mi familia es muy grande.",
    contextTarget: "familia",
    revision: 1,
  },
  {
    id: "v-a1-12",
    level: "A1",
    word: "escuela",
    translation: "школа",
    accept: ["школа"],
    context: "Los niños van a la escuela.",
    contextTarget: "escuela",
    revision: 1,
  },
  {
    id: "v-a1-13",
    level: "A1",
    word: "coche",
    translation: "машина",
    accept: ["машина", "автомобиль"],
    context: "Voy al trabajo en coche.",
    contextTarget: "coche",
    revision: 1,
  },
  {
    id: "v-a1-14",
    level: "A1",
    word: "dinero",
    translation: "деньги",
    accept: ["деньги"],
    context: "No tengo mucho dinero.",
    contextTarget: "dinero",
    revision: 1,
  },
] satisfies VocabularyCard[];
