import type { PlacementQuestion } from "../types";

export const placementQuestions = [
  {
    level: "A1",
    prompt: "Yo ___ estudiante.",
    options: ["soy", "estoy", "es", "eres"],
    answer: "soy",
    id: "placement-01",
    revision: 1,
  },
  {
    level: "A1",
    prompt: "Ella tiene ___ libros en su mesa.",
    options: ["unos", "una", "un", "unas"],
    answer: "unos",
    id: "placement-02",
    revision: 1,
  },
  {
    level: "A1",
    prompt: "Nosotros (vivir) ___ en Barcelona.",
    options: ["vivimos", "viven", "vivo", "vive"],
    answer: "vivimos",
    id: "placement-03",
    revision: 1,
  },
  {
    level: "A2",
    prompt: "Ayer (yo/ir) ___ al cine con mis amigos.",
    options: ["fui", "iba", "voy", "iré"],
    answer: "fui",
    id: "placement-04",
    revision: 1,
  },
  {
    level: "A2",
    prompt: "Cuando era niño, (yo) ___ en un pueblo pequeño.",
    options: ["vivía", "viví", "vivo", "he vivido"],
    answer: "vivía",
    id: "placement-05",
    revision: 1,
  },
  {
    level: "A2",
    prompt: "Mi hermana es ___ alta que yo.",
    options: ["más", "tan", "muy", "mucho"],
    answer: "más",
    id: "placement-06",
    revision: 1,
  },
  {
    level: "B1",
    prompt: "Espero que ___ un buen fin de semana.",
    options: ["tengas", "tienes", "tendrás", "tuvieras"],
    answer: "tengas",
    id: "placement-07",
    revision: 1,
  },
  {
    level: "B1",
    prompt: "Este café es ___ mí.",
    options: ["para", "por", "a", "de"],
    answer: "para",
    id: "placement-08",
    revision: 1,
  },
  {
    level: "B1",
    prompt: "Esta semana ya (yo/terminar) ___ el informe.",
    options: ["he terminado", "terminé", "terminaba", "terminaré"],
    answer: "he terminado",
    id: "placement-09",
    revision: 1,
  },
  {
    level: "B2",
    prompt: "Si (yo) ___ más tiempo, viajaría más.",
    options: ["tuviera", "tengo", "tendría", "tuve"],
    answer: "tuviera",
    id: "placement-10",
    revision: 1,
  },
  {
    level: "B2",
    prompt: "La casa ___ construida en 1990.",
    options: ["fue", "estuvo", "era", "fuera"],
    answer: "fue",
    id: "placement-11",
    revision: 1,
  },
  {
    level: "B2",
    prompt: "Aunque ___ mucho dinero, no sería feliz sin amigos.",
    options: ["tuviera", "tengo", "tendré", "tuve"],
    answer: "tuviera",
    id: "placement-12",
    revision: 1,
  },
  {
    level: "C1",
    prompt: "Por más que lo ___, no logro convencerlo.",
    options: ["intento", "intentara", "intentaré", "intentaba"],
    answer: "intento",
    id: "placement-13",
    revision: 1,
  },
  {
    level: "C1",
    prompt: "Busco a alguien que ___ resolver este problema.",
    options: ["sepa", "sabe", "sabrá", "supo"],
    answer: "sepa",
    id: "placement-14",
    revision: 1,
  },
  {
    level: "C1",
    prompt: "No te imaginas ___ difícil que fue la decisión.",
    options: ["lo", "que", "cuán", "el"],
    answer: "lo",
    id: "placement-15",
    revision: 1,
  },
] satisfies PlacementQuestion[];
