export const contentTopics = [
  "adjetivos — género",
  "artículos",
  "colocaciones",
  "comparativos",
  "comparativos — igualdad",
  "condicionales irreales",
  "condicionales reales",
  "concesivas",
  "concesivas — por muy...que",
  "concesivas complejas",
  "condicional — cortesía",
  "condicional simple",
  "condicional tipo 2",
  "condicional tipo 3",
  "conectores discursivos",
  "cuál vs qué",
  "discurso indirecto",
  "discurso indirecto complejo",
  "estar + gerundio",
  "estilo indirecto",
  "estructuras enfáticas",
  "expresiones de tiempo",
  "futuro compuesto",
  "futuro de probabilidad",
  "futuro simple",
  "gerundio",
  "gerundio causal",
  "gustar",
  "hay",
  "imperativo afirmativo",
  "imperativo formal",
  "imperativo negativo",
  "imperfecto",
  "ir + a",
  "lo que",
  "nominalización",
  "nominalización / registro formal",
  "objeto directo",
  "objeto indirecto",
  "pasiva refleja",
  "pasiva refleja vs ser",
  "perífrasis — volver a",
  "perífrasis verbales",
  "plural",
  "pluscuamperfecto",
  "por / para",
  "por / para avanzado",
  "posesivos",
  "preposiciones",
  "presente -ar",
  "presente -er",
  "presente -ir",
  "presente ser",
  "pretérito indefinido",
  "pretérito irregular",
  "pretérito perfecto",
  "pretérito vs imperfecto",
  "pronombres dobles",
  "pronombres relativos",
  "reflexivos",
  "se involuntario",
  "sea como sea",
  "ser / estar",
  "subjuntivo — antecedente negado",
  "subjuntivo — conjunciones temporales",
  "subjuntivo — deseo",
  "subjuntivo — duda/emoción",
  "subjuntivo — finalidad",
  "subjuntivo — opinión negada",
  "subjuntivo — formación",
  "subjuntivo — ojalá",
  "subjuntivo imperfecto",
  "subjuntivo relativo indefinido",
  "subjuntivo vs indicativo",
  "superlativos",
  "tener que",
  "tener que / hay que",
  "verbo tener",
  "verbos con preposición",
  "verbos de cambio",
  "voz pasiva",
] as const;

export type ContentTopic = (typeof contentTopics)[number];
