import type { GrammarExercise } from "../../types";

export const a2Grammar = [
  {
    id: "a2-01",
    level: "A2",
    topic: "pretérito indefinido",
    type: "fill",
    prompt: "Ayer yo (comprar) ___ un libro nuevo.",
    answer: "compre",
    explain:
      'Правильный глагол на -ar в претерите: compr<b>é</b>, compraste, compró, compramos, comprasteis, compraron. Для "yo" окончание -é.',
    revision: 1,
  },
  {
    id: "a2-02",
    level: "A2",
    topic: "pretérito irregular",
    type: "mcq",
    prompt: "El año pasado ellos ___ a España.",
    options: ["fueron", "fue", "fuimos", "van"],
    answer: "fueron",
    explain:
      'Глагол "ir" в претерите неправильный и совпадает с формами "ser": fui, fuiste, fue, fuimos, fuisteis, <b>fueron</b>.',
    revision: 1,
  },
  {
    id: "a2-03",
    level: "A2",
    topic: "imperfecto",
    type: "fill",
    prompt: "Cuando era niño, (jugar) ___ en el parque todos los días.",
    answer: "jugaba",
    explain:
      "Имперфект для повторяющихся действий в прошлом: jug<b>aba</b>, jugabas, jugaba, jugábamos, jugabais, jugaban.",
    revision: 1,
  },
  {
    id: "a2-04",
    level: "A2",
    topic: "pretérito vs imperfecto",
    type: "mcq",
    prompt: "Mientras (yo) ___ la cena, sonó el teléfono.",
    options: ["preparaba", "preparé", "he preparado", "prepararé"],
    answer: "preparaba",
    explain:
      'Имперфект описывает фоновое, длящееся действие ("готовил"), на фоне которого происходит другое, законченное действие в претерите ("зазвонил").',
    revision: 1,
  },
  {
    id: "a2-05",
    level: "A2",
    topic: "futuro simple",
    type: "fill",
    prompt: "El próximo año (nosotros/viajar) ___ a Perú.",
    answer: "viajaremos",
    explain:
      "Будущее простое время образуется от инфинитива + окончания: viajar<b>emos</b> (nosotros). Окончания одинаковы для всех трёх спряжений.",
    revision: 1,
  },
  {
    id: "a2-06",
    level: "A2",
    topic: "comparativos",
    type: "mcq",
    prompt: "Mi hermano es ___ alto ___ yo.",
    options: ["más / que", "tan / como", "menos / de", "muy / que"],
    answer: "más / que",
    explain:
      'Сравнение превосходства: "más + прилагательное + que". Для равенства используется "tan...como".',
    revision: 1,
  },
  {
    id: "a2-07",
    level: "A2",
    topic: "superlativos",
    type: "mcq",
    prompt: "Este es el restaurante ___ caro de la ciudad.",
    options: ["más", "tan", "muy", "tanto"],
    answer: "más",
    explain:
      'Превосходная степень: "el/la más + прилагательное + de": el restaurante más caro de la ciudad.',
    revision: 1,
  },
  {
    id: "a2-08",
    level: "A2",
    topic: "objeto directo",
    type: "mcq",
    prompt: "¿Tienes las llaves? Sí, ___ tengo aquí.",
    options: ["las", "los", "les", "la"],
    answer: "las",
    explain:
      'Местоимение прямого дополнения должно согласовываться в роде и числе: "las llaves" — ж.р. мн.ч. → <b>las</b>.',
    revision: 1,
  },
  {
    id: "a2-09",
    level: "A2",
    topic: "objeto indirecto",
    type: "mcq",
    prompt: "___ voy a dar un regalo a mi madre.",
    options: ["Le", "Lo", "La", "Les"],
    answer: "le",
    explain:
      "Косвенное дополнение единственного числа — <b>le</b> (независимо от рода): le doy un regalo a mi madre.",
    revision: 1,
  },
  {
    id: "a2-10",
    level: "A2",
    topic: "reflexivos",
    type: "fill",
    prompt: "Todos los días yo (levantarse) ___ a las siete.",
    answer: "me levanto",
    explain:
      "Возвратные глаголы требуют местоимения, согласованного с субъектом: me levanto, te levantas, se levanta...",
    revision: 1,
  },
  {
    id: "a2-11",
    level: "A2",
    topic: "estar + gerundio",
    type: "fill",
    prompt: "Ahora mismo (nosotros/comer) ___ ___ en un restaurante.",
    answer: "estamos comiendo",
    explain:
      'Конструкция "estar + gerundio" выражает действие, происходящее прямо сейчас: estamos comiendo.',
    revision: 1,
  },
  {
    id: "a2-12",
    level: "A2",
    topic: "tener que / hay que",
    type: "mcq",
    prompt: "___ estudiar mucho para aprobar el examen.",
    options: ["Hay que", "Tengo que", "Tienes que", "Hay de"],
    answer: "hay que",
    explain:
      '"Hay que" — безличная конструкция обязанности (для всех вообще). "Tener que" используется с конкретным субъектом: tengo que, tienes que...',
    revision: 1,
  },
  {
    id: "a2-13",
    level: "A2",
    topic: "imperfecto",
    type: "mcq",
    prompt: "Antes, mis padres ___ en el campo.",
    options: ["vivían", "vivieron", "viven", "han vivido"],
    answer: "vivían",
    explain:
      "Имперфект используется для повторяющихся/привычных действий в прошлом: vivían (жили когда-то регулярно).",
    revision: 1,
  },
  {
    id: "a2-14",
    level: "A2",
    topic: "pretérito irregular",
    type: "mcq",
    prompt: "Ayer (yo) ___ que estudiar toda la noche.",
    options: ["tuve", "tenía", "tengo", "tendré"],
    answer: "tuve",
    explain:
      "Tener в претерите — неправильный глагол с основой tuv-: tuve, tuviste, tuvo, tuvimos, tuvisteis, tuvieron.",
    revision: 1,
  },
  {
    id: "a2-15",
    level: "A2",
    topic: "reflexivos",
    type: "mcq",
    prompt: "¿A qué hora ___ acuestas?",
    options: ["te", "se", "me", "nos"],
    answer: "te",
    explain:
      'Возвратное местоимение должно совпадать с подлежащим: для "tú" — te acuestas.',
    revision: 1,
  },
  {
    id: "a2-16",
    level: "A2",
    topic: "futuro simple",
    type: "fill",
    prompt: "El sábado (ellos/llegar) ___ a las diez.",
    answer: "llegarán",
    explain:
      'Futuro simple = инфинитив + окончания. Для "ellos": llegar<b>án</b>.',
    revision: 1,
  },
  {
    id: "a2-17",
    level: "A2",
    topic: "estar + gerundio",
    type: "fill",
    prompt: "Ahora (yo/leer) ___ ___ un libro interesante.",
    answer: "estoy leyendo",
    explain:
      '"Estar + gerundio" — действие прямо сейчас. Gerundio глагола leer неправильный: leyendo (i → y между гласными).',
    revision: 1,
  },
  {
    id: "a2-18",
    level: "A2",
    topic: "comparativos — igualdad",
    type: "fill",
    prompt: "Ana es tan alta ___ su hermano.",
    answer: "como",
    explain:
      'Сравнение равенства: "tan + прилагательное + como" (так же... как).',
    revision: 1,
  },
  {
    id: "a2-19",
    level: "A2",
    topic: "objeto directo",
    type: "fill",
    prompt: "¿Compraste el pan? Sí, ___ compré esta mañana.",
    answer: "lo",
    explain:
      'Местоимение прямого дополнения для "el pan" (м.р. ед.ч.) — <b>lo</b>.',
    revision: 1,
  },
  {
    id: "a2-20",
    level: "A2",
    topic: "tener que",
    type: "fill",
    prompt: "Nosotros (tener que) ___ terminar el proyecto hoy.",
    answer: "tenemos que",
    explain:
      '"Tener que + infinitivo" выражает обязанность; глагол tener спрягается по подлежащему: nosotros → tenemos que.',
    revision: 1,
  },
] satisfies GrammarExercise[];
