import type { VocabularyCard } from "../../types";

export const a2Vocabulary = [
  {
    id: "v-a2-1",
    level: "A2",
    word: "viaje",
    translation: "путешествие",
    accept: ["путешествие", "поездка"],
    context: "Hicimos un viaje a Italia.",
    contextTarget: "viaje",
    revision: 1,
  },
  {
    id: "v-a2-2",
    level: "A2",
    word: "recuerdo",
    translation: "воспоминание",
    accept: ["воспоминание"],
    context: "Tengo un buen recuerdo de esas vacaciones.",
    contextTarget: "recuerdo",
    revision: 1,
  },
  {
    id: "v-a2-3",
    level: "A2",
    word: "costumbre",
    translation: "привычка",
    accept: ["привычка", "обычай"],
    context: "Es una costumbre muy antigua.",
    contextTarget: "costumbre",
    revision: 1,
  },
  {
    id: "v-a2-4",
    level: "A2",
    word: "empresa",
    translation: "компания",
    accept: ["компания", "фирма", "предприятие"],
    context: "Trabaja en una empresa grande.",
    contextTarget: "empresa",
    revision: 1,
  },
  {
    id: "v-a2-5",
    level: "A2",
    word: "reunión",
    translation: "встреча",
    accept: ["встреча", "собрание"],
    context: "Tenemos una reunión a las diez.",
    contextTarget: "reunión",
    revision: 1,
  },
  {
    id: "v-a2-6",
    level: "A2",
    word: "barrio",
    translation: "район",
    accept: ["район", "квартал"],
    context: "Vivo en un barrio tranquilo.",
    contextTarget: "barrio",
    revision: 1,
  },
  {
    id: "v-a2-7",
    level: "A2",
    word: "paisaje",
    translation: "пейзаж",
    accept: ["пейзаж", "вид"],
    context: "El paisaje de la montaña es precioso.",
    contextTarget: "paisaje",
    revision: 1,
  },
  {
    id: "v-a2-8",
    level: "A2",
    word: "entrevista",
    translation: "собеседование",
    accept: ["собеседование", "интервью"],
    context: "Mañana tengo una entrevista de trabajo.",
    contextTarget: "entrevista",
    revision: 1,
  },
  {
    id: "v-a2-9",
    level: "A2",
    word: "alegría",
    translation: "радость",
    accept: ["радость"],
    context: "Sintió una gran alegría al verlos.",
    contextTarget: "alegría",
    revision: 1,
  },
  {
    id: "v-a2-10",
    level: "A2",
    word: "vergüenza",
    translation: "стыд",
    accept: ["стыд", "смущение"],
    context: "Me dio vergüenza hablar en público.",
    contextTarget: "vergüenza",
    revision: 1,
  },
  {
    id: "v-a2-11",
    level: "A2",
    word: "paciencia",
    translation: "терпение",
    accept: ["терпение"],
    context: "Hay que tener paciencia con los niños.",
    contextTarget: "paciencia",
    revision: 1,
  },
  {
    id: "v-a2-12",
    level: "A2",
    word: "costa",
    translation: "побережье",
    accept: ["побережье", "берег"],
    context: "Pasamos el verano en la costa.",
    contextTarget: "costa",
    revision: 1,
  },
  {
    id: "v-a2-13",
    level: "A2",
    word: "horario",
    translation: "расписание",
    accept: ["расписание", "график"],
    context: "¿Cuál es tu horario de trabajo?",
    contextTarget: "horario",
    revision: 1,
  },
  {
    id: "v-a2-14",
    level: "A2",
    word: "equipaje",
    translation: "багаж",
    accept: ["багаж"],
    context: "Perdí mi equipaje en el aeropuerto.",
    contextTarget: "equipaje",
    revision: 1,
  },
] satisfies VocabularyCard[];
